/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Mux_timer.h>
#include <Clock_4.h>
#include <ISR.h>
#include <INPUT_SELECT.h>
#include <INPUT_SELECT_aliases.h>
#include <CONTROL.h>
#include <CONTROL_aliases.h>
#include <LED.h>
#include <LED_aliases.h>
#include <Drive_Right_MCU.h>
#include <Drive_Right_MCU_aliases.h>
#include <Drive_Right_Backup.h>
#include <Drive_Right_Backup_aliases.h>
#include <Drive_Left_MCU.h>
#include <Drive_Left_MCU_aliases.h>
#include <Drive_Left_Backup.h>
#include <Drive_Left_Backup_aliases.h>
#include <Camera_Pan_MCU.h>
#include <Camera_Pan_MCU_aliases.h>
#include <Camera_Pan_Backup.h>
#include <Camera_Pan_Backup_aliases.h>
#include <Camera_Tilt_MCU.h>
#include <Camera_Tilt_MCU_aliases.h>
#include <Camera_Tilt_Backup.h>
#include <Camera_Tilt_Backup_aliases.h>
#include <Drive_Right.h>
#include <Drive_Right_aliases.h>
#include <Drive_Left.h>
#include <Drive_Left_aliases.h>
#include <Camera_Pan.h>
#include <Camera_Pan_aliases.h>
#include <Camera_Tilt.h>
#include <Camera_Tilt_aliases.h>
#include <Default_PWM.h>
#include <Clock_1.h>
#include <ISR_1.h>
#include <Camera_select.h>
#include <Camera_select_aliases.h>
#include <Camera_Sel_Backup.h>
#include <Camera_Sel_Backup_aliases.h>
#include <Camera_Sel_MCU.h>
#include <Camera_Sel_MCU_aliases.h>
#include <Arm_select.h>
#include <Arm_select_aliases.h>
#include <ISR_3.h>
#include <Clock_3.h>
#include <Cam_sel_PWM.h>
#include <ISR_2.h>
#include <Clock_2.h>
#include <Cam_Sel_timer.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

