#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice_trm.h>

/* ISR */
#define ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR__INTC_MASK 0x10000u
#define ISR__INTC_NUMBER 16u
#define ISR__INTC_PRIOR_MASK 0xC0u
#define ISR__INTC_PRIOR_NUM 3u
#define ISR__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ISR_1 */
#define ISR_1__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR_1__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR_1__INTC_MASK 0x20000u
#define ISR_1__INTC_NUMBER 17u
#define ISR_1__INTC_PRIOR_MASK 0xC000u
#define ISR_1__INTC_PRIOR_NUM 3u
#define ISR_1__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR_1__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR_1__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ISR_2 */
#define ISR_2__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR_2__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR_2__INTC_MASK 0x40000u
#define ISR_2__INTC_NUMBER 18u
#define ISR_2__INTC_PRIOR_MASK 0xC00000u
#define ISR_2__INTC_PRIOR_NUM 3u
#define ISR_2__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR_2__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR_2__INTC_SET_PD_REG CYREG_CM0_ISPR

/* LED */
#define LED__0__DM__MASK 0x1C0000u
#define LED__0__DM__SHIFT 18
#define LED__0__DR CYREG_PRT1_DR
#define LED__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define LED__0__HSIOM_MASK 0x0F000000u
#define LED__0__HSIOM_SHIFT 24u
#define LED__0__INTCFG CYREG_PRT1_INTCFG
#define LED__0__INTSTAT CYREG_PRT1_INTSTAT
#define LED__0__MASK 0x40u
#define LED__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__0__PC CYREG_PRT1_PC
#define LED__0__PC2 CYREG_PRT1_PC2
#define LED__0__PORT 1u
#define LED__0__PS CYREG_PRT1_PS
#define LED__0__SHIFT 6
#define LED__DR CYREG_PRT1_DR
#define LED__INTCFG CYREG_PRT1_INTCFG
#define LED__INTSTAT CYREG_PRT1_INTSTAT
#define LED__MASK 0x40u
#define LED__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__PC CYREG_PRT1_PC
#define LED__PC2 CYREG_PRT1_PC2
#define LED__PORT 1u
#define LED__PS CYREG_PRT1_PS
#define LED__SHIFT 6

/* Out_1 */
#define Out_1__0__DM__MASK 0x38000u
#define Out_1__0__DM__SHIFT 15
#define Out_1__0__DR CYREG_PRT0_DR
#define Out_1__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_1__0__HSIOM_MASK 0x00F00000u
#define Out_1__0__HSIOM_SHIFT 20u
#define Out_1__0__INTCFG CYREG_PRT0_INTCFG
#define Out_1__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_1__0__MASK 0x20u
#define Out_1__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_1__0__OUT_SEL_SHIFT 10u
#define Out_1__0__OUT_SEL_VAL 2u
#define Out_1__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_1__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_1__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_1__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_1__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_1__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_1__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_1__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_1__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_1__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_1__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_1__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_1__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_1__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_1__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_1__0__PC CYREG_PRT0_PC
#define Out_1__0__PC2 CYREG_PRT0_PC2
#define Out_1__0__PORT 0u
#define Out_1__0__PS CYREG_PRT0_PS
#define Out_1__0__SHIFT 5
#define Out_1__DR CYREG_PRT0_DR
#define Out_1__INTCFG CYREG_PRT0_INTCFG
#define Out_1__INTSTAT CYREG_PRT0_INTSTAT
#define Out_1__MASK 0x20u
#define Out_1__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_1__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_1__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_1__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_1__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_1__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_1__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_1__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_1__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_1__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_1__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_1__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_1__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_1__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_1__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_1__PC CYREG_PRT0_PC
#define Out_1__PC2 CYREG_PRT0_PC2
#define Out_1__PORT 0u
#define Out_1__PS CYREG_PRT0_PS
#define Out_1__SHIFT 5

/* Out_2 */
#define Out_2__0__DM__MASK 0x7000u
#define Out_2__0__DM__SHIFT 12
#define Out_2__0__DR CYREG_PRT0_DR
#define Out_2__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_2__0__HSIOM_MASK 0x000F0000u
#define Out_2__0__HSIOM_SHIFT 16u
#define Out_2__0__INTCFG CYREG_PRT0_INTCFG
#define Out_2__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_2__0__MASK 0x10u
#define Out_2__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_2__0__OUT_SEL_SHIFT 8u
#define Out_2__0__OUT_SEL_VAL 3u
#define Out_2__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_2__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_2__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_2__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_2__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_2__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_2__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_2__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_2__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_2__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_2__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_2__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_2__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_2__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_2__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_2__0__PC CYREG_PRT0_PC
#define Out_2__0__PC2 CYREG_PRT0_PC2
#define Out_2__0__PORT 0u
#define Out_2__0__PS CYREG_PRT0_PS
#define Out_2__0__SHIFT 4
#define Out_2__DR CYREG_PRT0_DR
#define Out_2__INTCFG CYREG_PRT0_INTCFG
#define Out_2__INTSTAT CYREG_PRT0_INTSTAT
#define Out_2__MASK 0x10u
#define Out_2__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_2__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_2__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_2__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_2__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_2__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_2__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_2__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_2__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_2__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_2__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_2__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_2__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_2__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_2__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_2__PC CYREG_PRT0_PC
#define Out_2__PC2 CYREG_PRT0_PC2
#define Out_2__PORT 0u
#define Out_2__PS CYREG_PRT0_PS
#define Out_2__SHIFT 4

/* Out_3 */
#define Out_3__0__DM__MASK 0xE00u
#define Out_3__0__DM__SHIFT 9
#define Out_3__0__DR CYREG_PRT0_DR
#define Out_3__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_3__0__HSIOM_MASK 0x0000F000u
#define Out_3__0__HSIOM_SHIFT 12u
#define Out_3__0__INTCFG CYREG_PRT0_INTCFG
#define Out_3__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_3__0__MASK 0x08u
#define Out_3__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_3__0__OUT_SEL_SHIFT 6u
#define Out_3__0__OUT_SEL_VAL 1u
#define Out_3__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_3__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_3__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_3__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_3__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_3__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_3__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_3__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_3__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_3__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_3__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_3__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_3__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_3__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_3__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_3__0__PC CYREG_PRT0_PC
#define Out_3__0__PC2 CYREG_PRT0_PC2
#define Out_3__0__PORT 0u
#define Out_3__0__PS CYREG_PRT0_PS
#define Out_3__0__SHIFT 3
#define Out_3__DR CYREG_PRT0_DR
#define Out_3__INTCFG CYREG_PRT0_INTCFG
#define Out_3__INTSTAT CYREG_PRT0_INTSTAT
#define Out_3__MASK 0x08u
#define Out_3__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_3__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_3__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_3__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_3__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_3__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_3__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_3__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_3__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_3__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_3__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_3__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_3__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_3__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_3__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_3__PC CYREG_PRT0_PC
#define Out_3__PC2 CYREG_PRT0_PC2
#define Out_3__PORT 0u
#define Out_3__PS CYREG_PRT0_PS
#define Out_3__SHIFT 3

/* Out_4 */
#define Out_4__0__DM__MASK 0x1C0u
#define Out_4__0__DM__SHIFT 6
#define Out_4__0__DR CYREG_PRT0_DR
#define Out_4__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_4__0__HSIOM_MASK 0x00000F00u
#define Out_4__0__HSIOM_SHIFT 8u
#define Out_4__0__INTCFG CYREG_PRT0_INTCFG
#define Out_4__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_4__0__MASK 0x04u
#define Out_4__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_4__0__OUT_SEL_SHIFT 4u
#define Out_4__0__OUT_SEL_VAL 0u
#define Out_4__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_4__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_4__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_4__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_4__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_4__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_4__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_4__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_4__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_4__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_4__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_4__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_4__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_4__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_4__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_4__0__PC CYREG_PRT0_PC
#define Out_4__0__PC2 CYREG_PRT0_PC2
#define Out_4__0__PORT 0u
#define Out_4__0__PS CYREG_PRT0_PS
#define Out_4__0__SHIFT 2
#define Out_4__DR CYREG_PRT0_DR
#define Out_4__INTCFG CYREG_PRT0_INTCFG
#define Out_4__INTSTAT CYREG_PRT0_INTSTAT
#define Out_4__MASK 0x04u
#define Out_4__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_4__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_4__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_4__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_4__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_4__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_4__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_4__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_4__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_4__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_4__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_4__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_4__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_4__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_4__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_4__PC CYREG_PRT0_PC
#define Out_4__PC2 CYREG_PRT0_PC2
#define Out_4__PORT 0u
#define Out_4__PS CYREG_PRT0_PS
#define Out_4__SHIFT 2

/* Out_5 */
#define Out_5__0__DM__MASK 0x38u
#define Out_5__0__DM__SHIFT 3
#define Out_5__0__DR CYREG_PRT0_DR
#define Out_5__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_5__0__HSIOM_MASK 0x000000F0u
#define Out_5__0__HSIOM_SHIFT 4u
#define Out_5__0__INTCFG CYREG_PRT0_INTCFG
#define Out_5__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_5__0__MASK 0x02u
#define Out_5__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_5__0__OUT_SEL_SHIFT 2u
#define Out_5__0__OUT_SEL_VAL 3u
#define Out_5__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_5__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_5__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_5__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_5__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_5__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_5__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_5__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_5__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_5__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_5__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_5__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_5__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_5__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_5__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_5__0__PC CYREG_PRT0_PC
#define Out_5__0__PC2 CYREG_PRT0_PC2
#define Out_5__0__PORT 0u
#define Out_5__0__PS CYREG_PRT0_PS
#define Out_5__0__SHIFT 1
#define Out_5__DR CYREG_PRT0_DR
#define Out_5__INTCFG CYREG_PRT0_INTCFG
#define Out_5__INTSTAT CYREG_PRT0_INTSTAT
#define Out_5__MASK 0x02u
#define Out_5__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_5__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_5__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_5__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_5__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_5__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_5__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_5__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_5__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_5__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_5__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_5__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_5__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_5__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_5__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_5__PC CYREG_PRT0_PC
#define Out_5__PC2 CYREG_PRT0_PC2
#define Out_5__PORT 0u
#define Out_5__PS CYREG_PRT0_PS
#define Out_5__SHIFT 1

/* Out_6 */
#define Out_6__0__DM__MASK 0x07u
#define Out_6__0__DM__SHIFT 0
#define Out_6__0__DR CYREG_PRT0_DR
#define Out_6__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Out_6__0__HSIOM_MASK 0x0000000Fu
#define Out_6__0__HSIOM_SHIFT 0u
#define Out_6__0__INTCFG CYREG_PRT0_INTCFG
#define Out_6__0__INTSTAT CYREG_PRT0_INTSTAT
#define Out_6__0__MASK 0x01u
#define Out_6__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Out_6__0__OUT_SEL_SHIFT 0u
#define Out_6__0__OUT_SEL_VAL 2u
#define Out_6__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_6__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_6__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_6__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_6__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_6__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_6__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_6__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_6__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_6__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_6__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_6__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_6__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_6__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_6__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_6__0__PC CYREG_PRT0_PC
#define Out_6__0__PC2 CYREG_PRT0_PC2
#define Out_6__0__PORT 0u
#define Out_6__0__PS CYREG_PRT0_PS
#define Out_6__0__SHIFT 0
#define Out_6__DR CYREG_PRT0_DR
#define Out_6__INTCFG CYREG_PRT0_INTCFG
#define Out_6__INTSTAT CYREG_PRT0_INTSTAT
#define Out_6__MASK 0x01u
#define Out_6__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Out_6__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Out_6__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Out_6__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Out_6__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Out_6__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Out_6__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Out_6__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Out_6__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Out_6__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Out_6__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Out_6__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Out_6__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Out_6__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Out_6__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Out_6__PC CYREG_PRT0_PC
#define Out_6__PC2 CYREG_PRT0_PC2
#define Out_6__PORT 0u
#define Out_6__PS CYREG_PRT0_PS
#define Out_6__SHIFT 0

/* B_in_1 */
#define B_in_1__0__DM__MASK 0x38000u
#define B_in_1__0__DM__SHIFT 15
#define B_in_1__0__DR CYREG_PRT1_DR
#define B_in_1__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_1__0__HSIOM_MASK 0x00F00000u
#define B_in_1__0__HSIOM_SHIFT 20u
#define B_in_1__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_1__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_1__0__MASK 0x20u
#define B_in_1__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_1__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_1__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_1__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_1__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_1__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_1__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_1__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_1__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_1__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_1__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_1__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_1__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_1__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_1__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_1__0__PC CYREG_PRT1_PC
#define B_in_1__0__PC2 CYREG_PRT1_PC2
#define B_in_1__0__PORT 1u
#define B_in_1__0__PS CYREG_PRT1_PS
#define B_in_1__0__SHIFT 5
#define B_in_1__DR CYREG_PRT1_DR
#define B_in_1__INTCFG CYREG_PRT1_INTCFG
#define B_in_1__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_1__MASK 0x20u
#define B_in_1__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_1__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_1__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_1__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_1__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_1__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_1__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_1__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_1__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_1__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_1__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_1__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_1__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_1__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_1__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_1__PC CYREG_PRT1_PC
#define B_in_1__PC2 CYREG_PRT1_PC2
#define B_in_1__PORT 1u
#define B_in_1__PS CYREG_PRT1_PS
#define B_in_1__SHIFT 5

/* B_in_2 */
#define B_in_2__0__DM__MASK 0x7000u
#define B_in_2__0__DM__SHIFT 12
#define B_in_2__0__DR CYREG_PRT1_DR
#define B_in_2__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_2__0__HSIOM_MASK 0x000F0000u
#define B_in_2__0__HSIOM_SHIFT 16u
#define B_in_2__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_2__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_2__0__MASK 0x10u
#define B_in_2__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_2__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_2__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_2__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_2__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_2__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_2__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_2__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_2__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_2__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_2__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_2__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_2__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_2__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_2__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_2__0__PC CYREG_PRT1_PC
#define B_in_2__0__PC2 CYREG_PRT1_PC2
#define B_in_2__0__PORT 1u
#define B_in_2__0__PS CYREG_PRT1_PS
#define B_in_2__0__SHIFT 4
#define B_in_2__DR CYREG_PRT1_DR
#define B_in_2__INTCFG CYREG_PRT1_INTCFG
#define B_in_2__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_2__MASK 0x10u
#define B_in_2__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_2__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_2__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_2__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_2__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_2__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_2__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_2__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_2__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_2__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_2__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_2__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_2__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_2__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_2__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_2__PC CYREG_PRT1_PC
#define B_in_2__PC2 CYREG_PRT1_PC2
#define B_in_2__PORT 1u
#define B_in_2__PS CYREG_PRT1_PS
#define B_in_2__SHIFT 4

/* B_in_3 */
#define B_in_3__0__DM__MASK 0xE00u
#define B_in_3__0__DM__SHIFT 9
#define B_in_3__0__DR CYREG_PRT1_DR
#define B_in_3__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_3__0__HSIOM_MASK 0x0000F000u
#define B_in_3__0__HSIOM_SHIFT 12u
#define B_in_3__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_3__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_3__0__MASK 0x08u
#define B_in_3__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_3__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_3__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_3__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_3__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_3__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_3__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_3__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_3__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_3__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_3__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_3__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_3__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_3__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_3__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_3__0__PC CYREG_PRT1_PC
#define B_in_3__0__PC2 CYREG_PRT1_PC2
#define B_in_3__0__PORT 1u
#define B_in_3__0__PS CYREG_PRT1_PS
#define B_in_3__0__SHIFT 3
#define B_in_3__DR CYREG_PRT1_DR
#define B_in_3__INTCFG CYREG_PRT1_INTCFG
#define B_in_3__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_3__MASK 0x08u
#define B_in_3__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_3__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_3__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_3__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_3__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_3__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_3__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_3__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_3__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_3__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_3__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_3__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_3__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_3__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_3__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_3__PC CYREG_PRT1_PC
#define B_in_3__PC2 CYREG_PRT1_PC2
#define B_in_3__PORT 1u
#define B_in_3__PS CYREG_PRT1_PS
#define B_in_3__SHIFT 3

/* B_in_4 */
#define B_in_4__0__DM__MASK 0x1C0u
#define B_in_4__0__DM__SHIFT 6
#define B_in_4__0__DR CYREG_PRT1_DR
#define B_in_4__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_4__0__HSIOM_MASK 0x00000F00u
#define B_in_4__0__HSIOM_SHIFT 8u
#define B_in_4__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_4__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_4__0__MASK 0x04u
#define B_in_4__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_4__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_4__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_4__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_4__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_4__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_4__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_4__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_4__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_4__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_4__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_4__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_4__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_4__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_4__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_4__0__PC CYREG_PRT1_PC
#define B_in_4__0__PC2 CYREG_PRT1_PC2
#define B_in_4__0__PORT 1u
#define B_in_4__0__PS CYREG_PRT1_PS
#define B_in_4__0__SHIFT 2
#define B_in_4__DR CYREG_PRT1_DR
#define B_in_4__INTCFG CYREG_PRT1_INTCFG
#define B_in_4__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_4__MASK 0x04u
#define B_in_4__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_4__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_4__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_4__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_4__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_4__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_4__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_4__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_4__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_4__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_4__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_4__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_4__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_4__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_4__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_4__PC CYREG_PRT1_PC
#define B_in_4__PC2 CYREG_PRT1_PC2
#define B_in_4__PORT 1u
#define B_in_4__PS CYREG_PRT1_PS
#define B_in_4__SHIFT 2

/* B_in_5 */
#define B_in_5__0__DM__MASK 0x38u
#define B_in_5__0__DM__SHIFT 3
#define B_in_5__0__DR CYREG_PRT1_DR
#define B_in_5__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_5__0__HSIOM_MASK 0x000000F0u
#define B_in_5__0__HSIOM_SHIFT 4u
#define B_in_5__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_5__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_5__0__MASK 0x02u
#define B_in_5__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_5__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_5__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_5__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_5__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_5__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_5__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_5__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_5__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_5__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_5__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_5__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_5__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_5__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_5__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_5__0__PC CYREG_PRT1_PC
#define B_in_5__0__PC2 CYREG_PRT1_PC2
#define B_in_5__0__PORT 1u
#define B_in_5__0__PS CYREG_PRT1_PS
#define B_in_5__0__SHIFT 1
#define B_in_5__DR CYREG_PRT1_DR
#define B_in_5__INTCFG CYREG_PRT1_INTCFG
#define B_in_5__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_5__MASK 0x02u
#define B_in_5__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_5__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_5__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_5__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_5__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_5__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_5__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_5__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_5__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_5__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_5__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_5__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_5__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_5__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_5__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_5__PC CYREG_PRT1_PC
#define B_in_5__PC2 CYREG_PRT1_PC2
#define B_in_5__PORT 1u
#define B_in_5__PS CYREG_PRT1_PS
#define B_in_5__SHIFT 1

/* B_in_6 */
#define B_in_6__0__DM__MASK 0x07u
#define B_in_6__0__DM__SHIFT 0
#define B_in_6__0__DR CYREG_PRT1_DR
#define B_in_6__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define B_in_6__0__HSIOM_MASK 0x0000000Fu
#define B_in_6__0__HSIOM_SHIFT 0u
#define B_in_6__0__INTCFG CYREG_PRT1_INTCFG
#define B_in_6__0__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_6__0__MASK 0x01u
#define B_in_6__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_6__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_6__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_6__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_6__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_6__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_6__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_6__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_6__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_6__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_6__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_6__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_6__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_6__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_6__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_6__0__PC CYREG_PRT1_PC
#define B_in_6__0__PC2 CYREG_PRT1_PC2
#define B_in_6__0__PORT 1u
#define B_in_6__0__PS CYREG_PRT1_PS
#define B_in_6__0__SHIFT 0
#define B_in_6__DR CYREG_PRT1_DR
#define B_in_6__INTCFG CYREG_PRT1_INTCFG
#define B_in_6__INTSTAT CYREG_PRT1_INTSTAT
#define B_in_6__MASK 0x01u
#define B_in_6__PA__CFG0 CYREG_UDB_PA1_CFG0
#define B_in_6__PA__CFG1 CYREG_UDB_PA1_CFG1
#define B_in_6__PA__CFG10 CYREG_UDB_PA1_CFG10
#define B_in_6__PA__CFG11 CYREG_UDB_PA1_CFG11
#define B_in_6__PA__CFG12 CYREG_UDB_PA1_CFG12
#define B_in_6__PA__CFG13 CYREG_UDB_PA1_CFG13
#define B_in_6__PA__CFG14 CYREG_UDB_PA1_CFG14
#define B_in_6__PA__CFG2 CYREG_UDB_PA1_CFG2
#define B_in_6__PA__CFG3 CYREG_UDB_PA1_CFG3
#define B_in_6__PA__CFG4 CYREG_UDB_PA1_CFG4
#define B_in_6__PA__CFG5 CYREG_UDB_PA1_CFG5
#define B_in_6__PA__CFG6 CYREG_UDB_PA1_CFG6
#define B_in_6__PA__CFG7 CYREG_UDB_PA1_CFG7
#define B_in_6__PA__CFG8 CYREG_UDB_PA1_CFG8
#define B_in_6__PA__CFG9 CYREG_UDB_PA1_CFG9
#define B_in_6__PC CYREG_PRT1_PC
#define B_in_6__PC2 CYREG_PRT1_PC2
#define B_in_6__PORT 1u
#define B_in_6__PS CYREG_PRT1_PS
#define B_in_6__SHIFT 0

/* M_in_1 */
#define M_in_1__0__DM__MASK 0xE00u
#define M_in_1__0__DM__SHIFT 9
#define M_in_1__0__DR CYREG_PRT2_DR
#define M_in_1__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define M_in_1__0__HSIOM_MASK 0x0000F000u
#define M_in_1__0__HSIOM_SHIFT 12u
#define M_in_1__0__INTCFG CYREG_PRT2_INTCFG
#define M_in_1__0__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_1__0__MASK 0x08u
#define M_in_1__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_1__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_1__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_1__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_1__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_1__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_1__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_1__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_1__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_1__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_1__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_1__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_1__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_1__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_1__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_1__0__PC CYREG_PRT2_PC
#define M_in_1__0__PC2 CYREG_PRT2_PC2
#define M_in_1__0__PORT 2u
#define M_in_1__0__PS CYREG_PRT2_PS
#define M_in_1__0__SHIFT 3
#define M_in_1__DR CYREG_PRT2_DR
#define M_in_1__INTCFG CYREG_PRT2_INTCFG
#define M_in_1__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_1__MASK 0x08u
#define M_in_1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_1__PC CYREG_PRT2_PC
#define M_in_1__PC2 CYREG_PRT2_PC2
#define M_in_1__PORT 2u
#define M_in_1__PS CYREG_PRT2_PS
#define M_in_1__SHIFT 3

/* M_in_2 */
#define M_in_2__0__DM__MASK 0x7000u
#define M_in_2__0__DM__SHIFT 12
#define M_in_2__0__DR CYREG_PRT2_DR
#define M_in_2__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define M_in_2__0__HSIOM_MASK 0x000F0000u
#define M_in_2__0__HSIOM_SHIFT 16u
#define M_in_2__0__INTCFG CYREG_PRT2_INTCFG
#define M_in_2__0__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_2__0__MASK 0x10u
#define M_in_2__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_2__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_2__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_2__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_2__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_2__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_2__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_2__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_2__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_2__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_2__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_2__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_2__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_2__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_2__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_2__0__PC CYREG_PRT2_PC
#define M_in_2__0__PC2 CYREG_PRT2_PC2
#define M_in_2__0__PORT 2u
#define M_in_2__0__PS CYREG_PRT2_PS
#define M_in_2__0__SHIFT 4
#define M_in_2__DR CYREG_PRT2_DR
#define M_in_2__INTCFG CYREG_PRT2_INTCFG
#define M_in_2__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_2__MASK 0x10u
#define M_in_2__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_2__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_2__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_2__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_2__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_2__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_2__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_2__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_2__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_2__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_2__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_2__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_2__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_2__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_2__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_2__PC CYREG_PRT2_PC
#define M_in_2__PC2 CYREG_PRT2_PC2
#define M_in_2__PORT 2u
#define M_in_2__PS CYREG_PRT2_PS
#define M_in_2__SHIFT 4

/* M_in_3 */
#define M_in_3__0__DM__MASK 0x38000u
#define M_in_3__0__DM__SHIFT 15
#define M_in_3__0__DR CYREG_PRT2_DR
#define M_in_3__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define M_in_3__0__HSIOM_MASK 0x00F00000u
#define M_in_3__0__HSIOM_SHIFT 20u
#define M_in_3__0__INTCFG CYREG_PRT2_INTCFG
#define M_in_3__0__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_3__0__MASK 0x20u
#define M_in_3__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_3__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_3__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_3__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_3__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_3__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_3__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_3__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_3__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_3__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_3__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_3__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_3__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_3__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_3__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_3__0__PC CYREG_PRT2_PC
#define M_in_3__0__PC2 CYREG_PRT2_PC2
#define M_in_3__0__PORT 2u
#define M_in_3__0__PS CYREG_PRT2_PS
#define M_in_3__0__SHIFT 5
#define M_in_3__DR CYREG_PRT2_DR
#define M_in_3__INTCFG CYREG_PRT2_INTCFG
#define M_in_3__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_3__MASK 0x20u
#define M_in_3__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_3__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_3__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_3__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_3__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_3__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_3__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_3__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_3__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_3__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_3__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_3__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_3__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_3__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_3__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_3__PC CYREG_PRT2_PC
#define M_in_3__PC2 CYREG_PRT2_PC2
#define M_in_3__PORT 2u
#define M_in_3__PS CYREG_PRT2_PS
#define M_in_3__SHIFT 5

/* M_in_4 */
#define M_in_4__0__DM__MASK 0x1C0000u
#define M_in_4__0__DM__SHIFT 18
#define M_in_4__0__DR CYREG_PRT2_DR
#define M_in_4__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define M_in_4__0__HSIOM_MASK 0x0F000000u
#define M_in_4__0__HSIOM_SHIFT 24u
#define M_in_4__0__INTCFG CYREG_PRT2_INTCFG
#define M_in_4__0__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_4__0__MASK 0x40u
#define M_in_4__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_4__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_4__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_4__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_4__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_4__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_4__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_4__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_4__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_4__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_4__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_4__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_4__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_4__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_4__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_4__0__PC CYREG_PRT2_PC
#define M_in_4__0__PC2 CYREG_PRT2_PC2
#define M_in_4__0__PORT 2u
#define M_in_4__0__PS CYREG_PRT2_PS
#define M_in_4__0__SHIFT 6
#define M_in_4__DR CYREG_PRT2_DR
#define M_in_4__INTCFG CYREG_PRT2_INTCFG
#define M_in_4__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_4__MASK 0x40u
#define M_in_4__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_4__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_4__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_4__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_4__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_4__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_4__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_4__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_4__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_4__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_4__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_4__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_4__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_4__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_4__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_4__PC CYREG_PRT2_PC
#define M_in_4__PC2 CYREG_PRT2_PC2
#define M_in_4__PORT 2u
#define M_in_4__PS CYREG_PRT2_PS
#define M_in_4__SHIFT 6

/* M_in_5 */
#define M_in_5__0__DM__MASK 0xE00000u
#define M_in_5__0__DM__SHIFT 21
#define M_in_5__0__DR CYREG_PRT2_DR
#define M_in_5__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define M_in_5__0__HSIOM_MASK 0xF0000000u
#define M_in_5__0__HSIOM_SHIFT 28u
#define M_in_5__0__INTCFG CYREG_PRT2_INTCFG
#define M_in_5__0__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_5__0__MASK 0x80u
#define M_in_5__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_5__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_5__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_5__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_5__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_5__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_5__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_5__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_5__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_5__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_5__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_5__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_5__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_5__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_5__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_5__0__PC CYREG_PRT2_PC
#define M_in_5__0__PC2 CYREG_PRT2_PC2
#define M_in_5__0__PORT 2u
#define M_in_5__0__PS CYREG_PRT2_PS
#define M_in_5__0__SHIFT 7
#define M_in_5__DR CYREG_PRT2_DR
#define M_in_5__INTCFG CYREG_PRT2_INTCFG
#define M_in_5__INTSTAT CYREG_PRT2_INTSTAT
#define M_in_5__MASK 0x80u
#define M_in_5__PA__CFG0 CYREG_UDB_PA2_CFG0
#define M_in_5__PA__CFG1 CYREG_UDB_PA2_CFG1
#define M_in_5__PA__CFG10 CYREG_UDB_PA2_CFG10
#define M_in_5__PA__CFG11 CYREG_UDB_PA2_CFG11
#define M_in_5__PA__CFG12 CYREG_UDB_PA2_CFG12
#define M_in_5__PA__CFG13 CYREG_UDB_PA2_CFG13
#define M_in_5__PA__CFG14 CYREG_UDB_PA2_CFG14
#define M_in_5__PA__CFG2 CYREG_UDB_PA2_CFG2
#define M_in_5__PA__CFG3 CYREG_UDB_PA2_CFG3
#define M_in_5__PA__CFG4 CYREG_UDB_PA2_CFG4
#define M_in_5__PA__CFG5 CYREG_UDB_PA2_CFG5
#define M_in_5__PA__CFG6 CYREG_UDB_PA2_CFG6
#define M_in_5__PA__CFG7 CYREG_UDB_PA2_CFG7
#define M_in_5__PA__CFG8 CYREG_UDB_PA2_CFG8
#define M_in_5__PA__CFG9 CYREG_UDB_PA2_CFG9
#define M_in_5__PC CYREG_PRT2_PC
#define M_in_5__PC2 CYREG_PRT2_PC2
#define M_in_5__PORT 2u
#define M_in_5__PS CYREG_PRT2_PS
#define M_in_5__SHIFT 7

/* M_in_6 */
#define M_in_6__0__DM__MASK 0x07u
#define M_in_6__0__DM__SHIFT 0
#define M_in_6__0__DR CYREG_PRT3_DR
#define M_in_6__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define M_in_6__0__HSIOM_MASK 0x0000000Fu
#define M_in_6__0__HSIOM_SHIFT 0u
#define M_in_6__0__INTCFG CYREG_PRT3_INTCFG
#define M_in_6__0__INTSTAT CYREG_PRT3_INTSTAT
#define M_in_6__0__MASK 0x01u
#define M_in_6__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define M_in_6__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define M_in_6__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define M_in_6__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define M_in_6__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define M_in_6__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define M_in_6__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define M_in_6__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define M_in_6__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define M_in_6__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define M_in_6__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define M_in_6__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define M_in_6__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define M_in_6__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define M_in_6__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define M_in_6__0__PC CYREG_PRT3_PC
#define M_in_6__0__PC2 CYREG_PRT3_PC2
#define M_in_6__0__PORT 3u
#define M_in_6__0__PS CYREG_PRT3_PS
#define M_in_6__0__SHIFT 0
#define M_in_6__DR CYREG_PRT3_DR
#define M_in_6__INTCFG CYREG_PRT3_INTCFG
#define M_in_6__INTSTAT CYREG_PRT3_INTSTAT
#define M_in_6__MASK 0x01u
#define M_in_6__PA__CFG0 CYREG_UDB_PA3_CFG0
#define M_in_6__PA__CFG1 CYREG_UDB_PA3_CFG1
#define M_in_6__PA__CFG10 CYREG_UDB_PA3_CFG10
#define M_in_6__PA__CFG11 CYREG_UDB_PA3_CFG11
#define M_in_6__PA__CFG12 CYREG_UDB_PA3_CFG12
#define M_in_6__PA__CFG13 CYREG_UDB_PA3_CFG13
#define M_in_6__PA__CFG14 CYREG_UDB_PA3_CFG14
#define M_in_6__PA__CFG2 CYREG_UDB_PA3_CFG2
#define M_in_6__PA__CFG3 CYREG_UDB_PA3_CFG3
#define M_in_6__PA__CFG4 CYREG_UDB_PA3_CFG4
#define M_in_6__PA__CFG5 CYREG_UDB_PA3_CFG5
#define M_in_6__PA__CFG6 CYREG_UDB_PA3_CFG6
#define M_in_6__PA__CFG7 CYREG_UDB_PA3_CFG7
#define M_in_6__PA__CFG8 CYREG_UDB_PA3_CFG8
#define M_in_6__PA__CFG9 CYREG_UDB_PA3_CFG9
#define M_in_6__PC CYREG_PRT3_PC
#define M_in_6__PC2 CYREG_PRT3_PC2
#define M_in_6__PORT 3u
#define M_in_6__PS CYREG_PRT3_PS
#define M_in_6__SHIFT 0

/* CONTROL */
#define CONTROL__0__DM__MASK 0x1C0000u
#define CONTROL__0__DM__SHIFT 18
#define CONTROL__0__DR CYREG_PRT0_DR
#define CONTROL__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define CONTROL__0__HSIOM_MASK 0x0F000000u
#define CONTROL__0__HSIOM_SHIFT 24u
#define CONTROL__0__INTCFG CYREG_PRT0_INTCFG
#define CONTROL__0__INTSTAT CYREG_PRT0_INTSTAT
#define CONTROL__0__MASK 0x40u
#define CONTROL__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define CONTROL__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define CONTROL__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define CONTROL__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define CONTROL__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define CONTROL__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define CONTROL__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define CONTROL__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define CONTROL__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define CONTROL__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define CONTROL__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define CONTROL__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define CONTROL__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define CONTROL__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define CONTROL__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define CONTROL__0__PC CYREG_PRT0_PC
#define CONTROL__0__PC2 CYREG_PRT0_PC2
#define CONTROL__0__PORT 0u
#define CONTROL__0__PS CYREG_PRT0_PS
#define CONTROL__0__SHIFT 6
#define CONTROL__DR CYREG_PRT0_DR
#define CONTROL__INTCFG CYREG_PRT0_INTCFG
#define CONTROL__INTSTAT CYREG_PRT0_INTSTAT
#define CONTROL__MASK 0x40u
#define CONTROL__PA__CFG0 CYREG_UDB_PA0_CFG0
#define CONTROL__PA__CFG1 CYREG_UDB_PA0_CFG1
#define CONTROL__PA__CFG10 CYREG_UDB_PA0_CFG10
#define CONTROL__PA__CFG11 CYREG_UDB_PA0_CFG11
#define CONTROL__PA__CFG12 CYREG_UDB_PA0_CFG12
#define CONTROL__PA__CFG13 CYREG_UDB_PA0_CFG13
#define CONTROL__PA__CFG14 CYREG_UDB_PA0_CFG14
#define CONTROL__PA__CFG2 CYREG_UDB_PA0_CFG2
#define CONTROL__PA__CFG3 CYREG_UDB_PA0_CFG3
#define CONTROL__PA__CFG4 CYREG_UDB_PA0_CFG4
#define CONTROL__PA__CFG5 CYREG_UDB_PA0_CFG5
#define CONTROL__PA__CFG6 CYREG_UDB_PA0_CFG6
#define CONTROL__PA__CFG7 CYREG_UDB_PA0_CFG7
#define CONTROL__PA__CFG8 CYREG_UDB_PA0_CFG8
#define CONTROL__PA__CFG9 CYREG_UDB_PA0_CFG9
#define CONTROL__PC CYREG_PRT0_PC
#define CONTROL__PC2 CYREG_PRT0_PC2
#define CONTROL__PORT 0u
#define CONTROL__PS CYREG_PRT0_PS
#define CONTROL__SHIFT 6

/* Clock_1 */
#define Clock_1__DIVIDER_MASK 0x0000FFFFu
#define Clock_1__ENABLE CYREG_CLK_DIVIDER_C00
#define Clock_1__ENABLE_MASK 0x80000000u
#define Clock_1__MASK 0x80000000u
#define Clock_1__REGISTER CYREG_CLK_DIVIDER_C00

/* Clock_2 */
#define Clock_2__DIVIDER_MASK 0x0000FFFFu
#define Clock_2__ENABLE CYREG_CLK_DIVIDER_B00
#define Clock_2__ENABLE_MASK 0x80000000u
#define Clock_2__MASK 0x80000000u
#define Clock_2__REGISTER CYREG_CLK_DIVIDER_B00

/* Clock_4 */
#define Clock_4__DIVIDER_MASK 0x0000FFFFu
#define Clock_4__ENABLE CYREG_CLK_DIVIDER_A00
#define Clock_4__ENABLE_MASK 0x80000000u
#define Clock_4__MASK 0x80000000u
#define Clock_4__REGISTER CYREG_CLK_DIVIDER_A00

/* Mux_timer_cy_m0s8_tcpwm_1 */
#define Mux_timer_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT0_CC
#define Mux_timer_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT0_CC_BUFF
#define Mux_timer_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT0_COUNTER
#define Mux_timer_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT0_CTRL
#define Mux_timer_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT0_INTR
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT0_INTR_MASK
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT0_INTR_MASKED
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT0_INTR_SET
#define Mux_timer_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT0_PERIOD
#define Mux_timer_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT0_PERIOD_BUFF
#define Mux_timer_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT0_STATUS
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x01u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 0
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x100u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 8
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x1000000u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 24
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x10000u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 16
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x01u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 0
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x01u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 0
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_NUMBER 0u
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT0_TR_CTRL0
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT0_TR_CTRL1
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT0_TR_CTRL2

/* Arm_select */
#define Arm_select__0__DM__MASK 0x07u
#define Arm_select__0__DM__SHIFT 0
#define Arm_select__0__DR CYREG_PRT2_DR
#define Arm_select__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Arm_select__0__HSIOM_MASK 0x0000000Fu
#define Arm_select__0__HSIOM_SHIFT 0u
#define Arm_select__0__INTCFG CYREG_PRT2_INTCFG
#define Arm_select__0__INTSTAT CYREG_PRT2_INTSTAT
#define Arm_select__0__MASK 0x01u
#define Arm_select__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Arm_select__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Arm_select__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Arm_select__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Arm_select__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Arm_select__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Arm_select__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Arm_select__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Arm_select__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Arm_select__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Arm_select__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Arm_select__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Arm_select__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Arm_select__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Arm_select__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Arm_select__0__PC CYREG_PRT2_PC
#define Arm_select__0__PC2 CYREG_PRT2_PC2
#define Arm_select__0__PORT 2u
#define Arm_select__0__PS CYREG_PRT2_PS
#define Arm_select__0__SHIFT 0
#define Arm_select__DR CYREG_PRT2_DR
#define Arm_select__INTCFG CYREG_PRT2_INTCFG
#define Arm_select__INTSTAT CYREG_PRT2_INTSTAT
#define Arm_select__MASK 0x01u
#define Arm_select__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Arm_select__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Arm_select__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Arm_select__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Arm_select__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Arm_select__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Arm_select__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Arm_select__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Arm_select__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Arm_select__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Arm_select__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Arm_select__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Arm_select__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Arm_select__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Arm_select__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Arm_select__PC CYREG_PRT2_PC
#define Arm_select__PC2 CYREG_PRT2_PC2
#define Arm_select__PORT 2u
#define Arm_select__PS CYREG_PRT2_PS
#define Arm_select__SHIFT 0

/* Arm_select_in */
#define Arm_select_in__0__DM__MASK 0xE00000u
#define Arm_select_in__0__DM__SHIFT 21
#define Arm_select_in__0__DR CYREG_PRT0_DR
#define Arm_select_in__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Arm_select_in__0__HSIOM_MASK 0xF0000000u
#define Arm_select_in__0__HSIOM_SHIFT 28u
#define Arm_select_in__0__INTCFG CYREG_PRT0_INTCFG
#define Arm_select_in__0__INTSTAT CYREG_PRT0_INTSTAT
#define Arm_select_in__0__MASK 0x80u
#define Arm_select_in__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Arm_select_in__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Arm_select_in__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Arm_select_in__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Arm_select_in__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Arm_select_in__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Arm_select_in__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Arm_select_in__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Arm_select_in__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Arm_select_in__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Arm_select_in__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Arm_select_in__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Arm_select_in__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Arm_select_in__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Arm_select_in__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Arm_select_in__0__PC CYREG_PRT0_PC
#define Arm_select_in__0__PC2 CYREG_PRT0_PC2
#define Arm_select_in__0__PORT 0u
#define Arm_select_in__0__PS CYREG_PRT0_PS
#define Arm_select_in__0__SHIFT 7
#define Arm_select_in__DR CYREG_PRT0_DR
#define Arm_select_in__INTCFG CYREG_PRT0_INTCFG
#define Arm_select_in__INTSTAT CYREG_PRT0_INTSTAT
#define Arm_select_in__MASK 0x80u
#define Arm_select_in__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Arm_select_in__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Arm_select_in__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Arm_select_in__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Arm_select_in__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Arm_select_in__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Arm_select_in__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Arm_select_in__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Arm_select_in__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Arm_select_in__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Arm_select_in__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Arm_select_in__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Arm_select_in__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Arm_select_in__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Arm_select_in__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Arm_select_in__PC CYREG_PRT0_PC
#define Arm_select_in__PC2 CYREG_PRT0_PC2
#define Arm_select_in__PORT 0u
#define Arm_select_in__PS CYREG_PRT0_PS
#define Arm_select_in__SHIFT 7

/* Arm_select_timer_cy_m0s8_tcpwm_1 */
#define Arm_select_timer_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT2_CC
#define Arm_select_timer_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT2_CC_BUFF
#define Arm_select_timer_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT2_COUNTER
#define Arm_select_timer_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT2_CTRL
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT2_INTR
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT2_INTR_MASK
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT2_INTR_MASKED
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT2_INTR_SET
#define Arm_select_timer_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT2_PERIOD
#define Arm_select_timer_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT2_PERIOD_BUFF
#define Arm_select_timer_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT2_STATUS
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x400u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 10
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x4000000u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 26
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x40000u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 18
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_NUMBER 2u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT2_TR_CTRL0
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT2_TR_CTRL1
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT2_TR_CTRL2

/* Default_PWM_cy_m0s8_tcpwm_1 */
#define Default_PWM_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT1_CC
#define Default_PWM_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT1_CC_BUFF
#define Default_PWM_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT1_COUNTER
#define Default_PWM_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT1_CTRL
#define Default_PWM_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT1_INTR
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT1_INTR_MASK
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT1_INTR_MASKED
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT1_INTR_SET
#define Default_PWM_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT1_PERIOD
#define Default_PWM_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT1_PERIOD_BUFF
#define Default_PWM_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT1_STATUS
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x02u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 1
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x200u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 9
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x2000000u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 25
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x20000u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 17
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x02u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 1
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x02u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 1
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_NUMBER 1u
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT1_TR_CTRL0
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT1_TR_CTRL1
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT1_TR_CTRL2

/* INPUT_SELECT */
#define INPUT_SELECT__0__DM__MASK 0x38u
#define INPUT_SELECT__0__DM__SHIFT 3
#define INPUT_SELECT__0__DR CYREG_PRT2_DR
#define INPUT_SELECT__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define INPUT_SELECT__0__HSIOM_MASK 0x000000F0u
#define INPUT_SELECT__0__HSIOM_SHIFT 4u
#define INPUT_SELECT__0__INTCFG CYREG_PRT2_INTCFG
#define INPUT_SELECT__0__INTSTAT CYREG_PRT2_INTSTAT
#define INPUT_SELECT__0__MASK 0x02u
#define INPUT_SELECT__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define INPUT_SELECT__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define INPUT_SELECT__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define INPUT_SELECT__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define INPUT_SELECT__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define INPUT_SELECT__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define INPUT_SELECT__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define INPUT_SELECT__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define INPUT_SELECT__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define INPUT_SELECT__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define INPUT_SELECT__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define INPUT_SELECT__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define INPUT_SELECT__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define INPUT_SELECT__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define INPUT_SELECT__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define INPUT_SELECT__0__PC CYREG_PRT2_PC
#define INPUT_SELECT__0__PC2 CYREG_PRT2_PC2
#define INPUT_SELECT__0__PORT 2u
#define INPUT_SELECT__0__PS CYREG_PRT2_PS
#define INPUT_SELECT__0__SHIFT 1
#define INPUT_SELECT__1__DM__MASK 0x1C0u
#define INPUT_SELECT__1__DM__SHIFT 6
#define INPUT_SELECT__1__DR CYREG_PRT2_DR
#define INPUT_SELECT__1__HSIOM CYREG_HSIOM_PORT_SEL2
#define INPUT_SELECT__1__HSIOM_MASK 0x00000F00u
#define INPUT_SELECT__1__HSIOM_SHIFT 8u
#define INPUT_SELECT__1__INTCFG CYREG_PRT2_INTCFG
#define INPUT_SELECT__1__INTSTAT CYREG_PRT2_INTSTAT
#define INPUT_SELECT__1__MASK 0x04u
#define INPUT_SELECT__1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define INPUT_SELECT__1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define INPUT_SELECT__1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define INPUT_SELECT__1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define INPUT_SELECT__1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define INPUT_SELECT__1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define INPUT_SELECT__1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define INPUT_SELECT__1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define INPUT_SELECT__1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define INPUT_SELECT__1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define INPUT_SELECT__1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define INPUT_SELECT__1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define INPUT_SELECT__1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define INPUT_SELECT__1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define INPUT_SELECT__1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define INPUT_SELECT__1__PC CYREG_PRT2_PC
#define INPUT_SELECT__1__PC2 CYREG_PRT2_PC2
#define INPUT_SELECT__1__PORT 2u
#define INPUT_SELECT__1__PS CYREG_PRT2_PS
#define INPUT_SELECT__1__SHIFT 2
#define INPUT_SELECT__DR CYREG_PRT2_DR
#define INPUT_SELECT__INTCFG CYREG_PRT2_INTCFG
#define INPUT_SELECT__INTSTAT CYREG_PRT2_INTSTAT
#define INPUT_SELECT__MASK 0x06u
#define INPUT_SELECT__PA__CFG0 CYREG_UDB_PA2_CFG0
#define INPUT_SELECT__PA__CFG1 CYREG_UDB_PA2_CFG1
#define INPUT_SELECT__PA__CFG10 CYREG_UDB_PA2_CFG10
#define INPUT_SELECT__PA__CFG11 CYREG_UDB_PA2_CFG11
#define INPUT_SELECT__PA__CFG12 CYREG_UDB_PA2_CFG12
#define INPUT_SELECT__PA__CFG13 CYREG_UDB_PA2_CFG13
#define INPUT_SELECT__PA__CFG14 CYREG_UDB_PA2_CFG14
#define INPUT_SELECT__PA__CFG2 CYREG_UDB_PA2_CFG2
#define INPUT_SELECT__PA__CFG3 CYREG_UDB_PA2_CFG3
#define INPUT_SELECT__PA__CFG4 CYREG_UDB_PA2_CFG4
#define INPUT_SELECT__PA__CFG5 CYREG_UDB_PA2_CFG5
#define INPUT_SELECT__PA__CFG6 CYREG_UDB_PA2_CFG6
#define INPUT_SELECT__PA__CFG7 CYREG_UDB_PA2_CFG7
#define INPUT_SELECT__PA__CFG8 CYREG_UDB_PA2_CFG8
#define INPUT_SELECT__PA__CFG9 CYREG_UDB_PA2_CFG9
#define INPUT_SELECT__PC CYREG_PRT2_PC
#define INPUT_SELECT__PC2 CYREG_PRT2_PC2
#define INPUT_SELECT__PORT 2u
#define INPUT_SELECT__PS CYREG_PRT2_PS
#define INPUT_SELECT__SHIFT 1

/* Miscellaneous */
#define CY_VERSION "PSoC Creator  3.1 SP1"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 6u
#define CYDEV_CHIP_DIE_PSOC4A 3u
#define CYDEV_CHIP_DIE_PSOC5LP 5u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 3u
#define CYDEV_CHIP_MEMBER_4D 2u
#define CYDEV_CHIP_MEMBER_4F 4u
#define CYDEV_CHIP_MEMBER_5A 6u
#define CYDEV_CHIP_MEMBER_5B 5u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0200
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
