#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice_trm.h>

/* ISR */
#define ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR__INTC_MASK 0x20000u
#define ISR__INTC_NUMBER 17u
#define ISR__INTC_PRIOR_MASK 0xC000u
#define ISR__INTC_PRIOR_NUM 3u
#define ISR__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ISR_1 */
#define ISR_1__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR_1__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR_1__INTC_MASK 0x10000u
#define ISR_1__INTC_NUMBER 16u
#define ISR_1__INTC_PRIOR_MASK 0xC0u
#define ISR_1__INTC_PRIOR_NUM 3u
#define ISR_1__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR_1__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR_1__INTC_SET_PD_REG CYREG_CM0_ISPR

/* ISR_2 */
#define ISR_2__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ISR_2__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ISR_2__INTC_MASK 0x40000u
#define ISR_2__INTC_NUMBER 18u
#define ISR_2__INTC_PRIOR_MASK 0xC00000u
#define ISR_2__INTC_PRIOR_NUM 3u
#define ISR_2__INTC_PRIOR_REG CYREG_CM0_IPR4
#define ISR_2__INTC_SET_EN_REG CYREG_CM0_ISER
#define ISR_2__INTC_SET_PD_REG CYREG_CM0_ISPR

/* LED */
#define LED__0__DM__MASK 0x1C0000u
#define LED__0__DM__SHIFT 18
#define LED__0__DR CYREG_PRT1_DR
#define LED__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define LED__0__HSIOM_MASK 0x0F000000u
#define LED__0__HSIOM_SHIFT 24u
#define LED__0__INTCFG CYREG_PRT1_INTCFG
#define LED__0__INTSTAT CYREG_PRT1_INTSTAT
#define LED__0__MASK 0x40u
#define LED__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__0__PC CYREG_PRT1_PC
#define LED__0__PC2 CYREG_PRT1_PC2
#define LED__0__PORT 1u
#define LED__0__PS CYREG_PRT1_PS
#define LED__0__SHIFT 6
#define LED__DR CYREG_PRT1_DR
#define LED__INTCFG CYREG_PRT1_INTCFG
#define LED__INTSTAT CYREG_PRT1_INTSTAT
#define LED__MASK 0x40u
#define LED__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LED__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LED__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LED__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LED__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LED__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LED__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LED__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LED__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LED__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LED__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LED__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LED__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LED__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LED__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LED__PC CYREG_PRT1_PC
#define LED__PC2 CYREG_PRT1_PC2
#define LED__PORT 1u
#define LED__PS CYREG_PRT1_PS
#define LED__SHIFT 6

/* Hand */
#define Hand__0__DM__MASK 0x07u
#define Hand__0__DM__SHIFT 0
#define Hand__0__DR CYREG_PRT3_DR
#define Hand__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define Hand__0__HSIOM_MASK 0x0000000Fu
#define Hand__0__HSIOM_SHIFT 0u
#define Hand__0__INTCFG CYREG_PRT3_INTCFG
#define Hand__0__INTSTAT CYREG_PRT3_INTSTAT
#define Hand__0__MASK 0x01u
#define Hand__0__OUT_SEL CYREG_UDB_PA3_CFG10
#define Hand__0__OUT_SEL_SHIFT 0u
#define Hand__0__OUT_SEL_VAL 3u
#define Hand__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define Hand__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define Hand__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define Hand__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define Hand__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define Hand__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define Hand__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define Hand__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define Hand__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define Hand__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define Hand__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define Hand__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define Hand__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define Hand__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define Hand__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define Hand__0__PC CYREG_PRT3_PC
#define Hand__0__PC2 CYREG_PRT3_PC2
#define Hand__0__PORT 3u
#define Hand__0__PS CYREG_PRT3_PS
#define Hand__0__SHIFT 0
#define Hand__DR CYREG_PRT3_DR
#define Hand__INTCFG CYREG_PRT3_INTCFG
#define Hand__INTSTAT CYREG_PRT3_INTSTAT
#define Hand__MASK 0x01u
#define Hand__PA__CFG0 CYREG_UDB_PA3_CFG0
#define Hand__PA__CFG1 CYREG_UDB_PA3_CFG1
#define Hand__PA__CFG10 CYREG_UDB_PA3_CFG10
#define Hand__PA__CFG11 CYREG_UDB_PA3_CFG11
#define Hand__PA__CFG12 CYREG_UDB_PA3_CFG12
#define Hand__PA__CFG13 CYREG_UDB_PA3_CFG13
#define Hand__PA__CFG14 CYREG_UDB_PA3_CFG14
#define Hand__PA__CFG2 CYREG_UDB_PA3_CFG2
#define Hand__PA__CFG3 CYREG_UDB_PA3_CFG3
#define Hand__PA__CFG4 CYREG_UDB_PA3_CFG4
#define Hand__PA__CFG5 CYREG_UDB_PA3_CFG5
#define Hand__PA__CFG6 CYREG_UDB_PA3_CFG6
#define Hand__PA__CFG7 CYREG_UDB_PA3_CFG7
#define Hand__PA__CFG8 CYREG_UDB_PA3_CFG8
#define Hand__PA__CFG9 CYREG_UDB_PA3_CFG9
#define Hand__PC CYREG_PRT3_PC
#define Hand__PC2 CYREG_PRT3_PC2
#define Hand__PORT 3u
#define Hand__PS CYREG_PRT3_PS
#define Hand__SHIFT 0

/* Hand_Backup */
#define Hand_Backup__0__DM__MASK 0xE00000u
#define Hand_Backup__0__DM__SHIFT 21
#define Hand_Backup__0__DR CYREG_PRT2_DR
#define Hand_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Hand_Backup__0__HSIOM_MASK 0xF0000000u
#define Hand_Backup__0__HSIOM_SHIFT 28u
#define Hand_Backup__0__INTCFG CYREG_PRT2_INTCFG
#define Hand_Backup__0__INTSTAT CYREG_PRT2_INTSTAT
#define Hand_Backup__0__MASK 0x80u
#define Hand_Backup__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Hand_Backup__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Hand_Backup__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Hand_Backup__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Hand_Backup__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Hand_Backup__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Hand_Backup__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Hand_Backup__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Hand_Backup__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Hand_Backup__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Hand_Backup__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Hand_Backup__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Hand_Backup__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Hand_Backup__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Hand_Backup__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Hand_Backup__0__PC CYREG_PRT2_PC
#define Hand_Backup__0__PC2 CYREG_PRT2_PC2
#define Hand_Backup__0__PORT 2u
#define Hand_Backup__0__PS CYREG_PRT2_PS
#define Hand_Backup__0__SHIFT 7
#define Hand_Backup__DR CYREG_PRT2_DR
#define Hand_Backup__INTCFG CYREG_PRT2_INTCFG
#define Hand_Backup__INTSTAT CYREG_PRT2_INTSTAT
#define Hand_Backup__MASK 0x80u
#define Hand_Backup__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Hand_Backup__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Hand_Backup__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Hand_Backup__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Hand_Backup__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Hand_Backup__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Hand_Backup__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Hand_Backup__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Hand_Backup__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Hand_Backup__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Hand_Backup__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Hand_Backup__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Hand_Backup__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Hand_Backup__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Hand_Backup__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Hand_Backup__PC CYREG_PRT2_PC
#define Hand_Backup__PC2 CYREG_PRT2_PC2
#define Hand_Backup__PORT 2u
#define Hand_Backup__PS CYREG_PRT2_PS
#define Hand_Backup__SHIFT 7

/* Hand_MCU */
#define Hand_MCU__0__DM__MASK 0x1C0000u
#define Hand_MCU__0__DM__SHIFT 18
#define Hand_MCU__0__DR CYREG_PRT2_DR
#define Hand_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Hand_MCU__0__HSIOM_MASK 0x0F000000u
#define Hand_MCU__0__HSIOM_SHIFT 24u
#define Hand_MCU__0__INTCFG CYREG_PRT2_INTCFG
#define Hand_MCU__0__INTSTAT CYREG_PRT2_INTSTAT
#define Hand_MCU__0__MASK 0x40u
#define Hand_MCU__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Hand_MCU__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Hand_MCU__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Hand_MCU__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Hand_MCU__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Hand_MCU__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Hand_MCU__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Hand_MCU__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Hand_MCU__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Hand_MCU__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Hand_MCU__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Hand_MCU__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Hand_MCU__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Hand_MCU__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Hand_MCU__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Hand_MCU__0__PC CYREG_PRT2_PC
#define Hand_MCU__0__PC2 CYREG_PRT2_PC2
#define Hand_MCU__0__PORT 2u
#define Hand_MCU__0__PS CYREG_PRT2_PS
#define Hand_MCU__0__SHIFT 6
#define Hand_MCU__DR CYREG_PRT2_DR
#define Hand_MCU__INTCFG CYREG_PRT2_INTCFG
#define Hand_MCU__INTSTAT CYREG_PRT2_INTSTAT
#define Hand_MCU__MASK 0x40u
#define Hand_MCU__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Hand_MCU__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Hand_MCU__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Hand_MCU__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Hand_MCU__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Hand_MCU__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Hand_MCU__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Hand_MCU__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Hand_MCU__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Hand_MCU__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Hand_MCU__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Hand_MCU__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Hand_MCU__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Hand_MCU__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Hand_MCU__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Hand_MCU__PC CYREG_PRT2_PC
#define Hand_MCU__PC2 CYREG_PRT2_PC2
#define Hand_MCU__PORT 2u
#define Hand_MCU__PS CYREG_PRT2_PS
#define Hand_MCU__SHIFT 6

/* Elbow */
#define Elbow__0__DM__MASK 0x38000u
#define Elbow__0__DM__SHIFT 15
#define Elbow__0__DR CYREG_PRT0_DR
#define Elbow__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Elbow__0__HSIOM_MASK 0x00F00000u
#define Elbow__0__HSIOM_SHIFT 20u
#define Elbow__0__INTCFG CYREG_PRT0_INTCFG
#define Elbow__0__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow__0__MASK 0x20u
#define Elbow__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define Elbow__0__OUT_SEL_SHIFT 10u
#define Elbow__0__OUT_SEL_VAL 2u
#define Elbow__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow__0__PC CYREG_PRT0_PC
#define Elbow__0__PC2 CYREG_PRT0_PC2
#define Elbow__0__PORT 0u
#define Elbow__0__PS CYREG_PRT0_PS
#define Elbow__0__SHIFT 5
#define Elbow__DR CYREG_PRT0_DR
#define Elbow__INTCFG CYREG_PRT0_INTCFG
#define Elbow__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow__MASK 0x20u
#define Elbow__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow__PC CYREG_PRT0_PC
#define Elbow__PC2 CYREG_PRT0_PC2
#define Elbow__PORT 0u
#define Elbow__PS CYREG_PRT0_PS
#define Elbow__SHIFT 5

/* Elbow_Backup */
#define Elbow_Backup__0__DM__MASK 0x1C0000u
#define Elbow_Backup__0__DM__SHIFT 18
#define Elbow_Backup__0__DR CYREG_PRT0_DR
#define Elbow_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Elbow_Backup__0__HSIOM_MASK 0x0F000000u
#define Elbow_Backup__0__HSIOM_SHIFT 24u
#define Elbow_Backup__0__INTCFG CYREG_PRT0_INTCFG
#define Elbow_Backup__0__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow_Backup__0__MASK 0x40u
#define Elbow_Backup__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow_Backup__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow_Backup__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow_Backup__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow_Backup__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow_Backup__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow_Backup__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow_Backup__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow_Backup__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow_Backup__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow_Backup__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow_Backup__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow_Backup__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow_Backup__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow_Backup__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow_Backup__0__PC CYREG_PRT0_PC
#define Elbow_Backup__0__PC2 CYREG_PRT0_PC2
#define Elbow_Backup__0__PORT 0u
#define Elbow_Backup__0__PS CYREG_PRT0_PS
#define Elbow_Backup__0__SHIFT 6
#define Elbow_Backup__DR CYREG_PRT0_DR
#define Elbow_Backup__INTCFG CYREG_PRT0_INTCFG
#define Elbow_Backup__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow_Backup__MASK 0x40u
#define Elbow_Backup__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow_Backup__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow_Backup__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow_Backup__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow_Backup__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow_Backup__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow_Backup__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow_Backup__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow_Backup__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow_Backup__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow_Backup__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow_Backup__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow_Backup__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow_Backup__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow_Backup__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow_Backup__PC CYREG_PRT0_PC
#define Elbow_Backup__PC2 CYREG_PRT0_PC2
#define Elbow_Backup__PORT 0u
#define Elbow_Backup__PS CYREG_PRT0_PS
#define Elbow_Backup__SHIFT 6

/* Elbow_MCU */
#define Elbow_MCU__0__DM__MASK 0xE00000u
#define Elbow_MCU__0__DM__SHIFT 21
#define Elbow_MCU__0__DR CYREG_PRT0_DR
#define Elbow_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Elbow_MCU__0__HSIOM_MASK 0xF0000000u
#define Elbow_MCU__0__HSIOM_SHIFT 28u
#define Elbow_MCU__0__INTCFG CYREG_PRT0_INTCFG
#define Elbow_MCU__0__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow_MCU__0__MASK 0x80u
#define Elbow_MCU__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow_MCU__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow_MCU__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow_MCU__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow_MCU__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow_MCU__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow_MCU__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow_MCU__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow_MCU__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow_MCU__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow_MCU__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow_MCU__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow_MCU__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow_MCU__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow_MCU__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow_MCU__0__PC CYREG_PRT0_PC
#define Elbow_MCU__0__PC2 CYREG_PRT0_PC2
#define Elbow_MCU__0__PORT 0u
#define Elbow_MCU__0__PS CYREG_PRT0_PS
#define Elbow_MCU__0__SHIFT 7
#define Elbow_MCU__DR CYREG_PRT0_DR
#define Elbow_MCU__INTCFG CYREG_PRT0_INTCFG
#define Elbow_MCU__INTSTAT CYREG_PRT0_INTSTAT
#define Elbow_MCU__MASK 0x80u
#define Elbow_MCU__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Elbow_MCU__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Elbow_MCU__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Elbow_MCU__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Elbow_MCU__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Elbow_MCU__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Elbow_MCU__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Elbow_MCU__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Elbow_MCU__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Elbow_MCU__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Elbow_MCU__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Elbow_MCU__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Elbow_MCU__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Elbow_MCU__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Elbow_MCU__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Elbow_MCU__PC CYREG_PRT0_PC
#define Elbow_MCU__PC2 CYREG_PRT0_PC2
#define Elbow_MCU__PORT 0u
#define Elbow_MCU__PS CYREG_PRT0_PS
#define Elbow_MCU__SHIFT 7

/* Turret */
#define Turret__0__DM__MASK 0xE00u
#define Turret__0__DM__SHIFT 9
#define Turret__0__DR CYREG_PRT1_DR
#define Turret__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Turret__0__HSIOM_MASK 0x0000F000u
#define Turret__0__HSIOM_SHIFT 12u
#define Turret__0__INTCFG CYREG_PRT1_INTCFG
#define Turret__0__INTSTAT CYREG_PRT1_INTSTAT
#define Turret__0__MASK 0x08u
#define Turret__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Turret__0__OUT_SEL_SHIFT 6u
#define Turret__0__OUT_SEL_VAL 1u
#define Turret__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret__0__PC CYREG_PRT1_PC
#define Turret__0__PC2 CYREG_PRT1_PC2
#define Turret__0__PORT 1u
#define Turret__0__PS CYREG_PRT1_PS
#define Turret__0__SHIFT 3
#define Turret__DR CYREG_PRT1_DR
#define Turret__INTCFG CYREG_PRT1_INTCFG
#define Turret__INTSTAT CYREG_PRT1_INTSTAT
#define Turret__MASK 0x08u
#define Turret__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret__PC CYREG_PRT1_PC
#define Turret__PC2 CYREG_PRT1_PC2
#define Turret__PORT 1u
#define Turret__PS CYREG_PRT1_PS
#define Turret__SHIFT 3

/* Turret_Backup */
#define Turret_Backup__0__DM__MASK 0x7000u
#define Turret_Backup__0__DM__SHIFT 12
#define Turret_Backup__0__DR CYREG_PRT1_DR
#define Turret_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Turret_Backup__0__HSIOM_MASK 0x000F0000u
#define Turret_Backup__0__HSIOM_SHIFT 16u
#define Turret_Backup__0__INTCFG CYREG_PRT1_INTCFG
#define Turret_Backup__0__INTSTAT CYREG_PRT1_INTSTAT
#define Turret_Backup__0__MASK 0x10u
#define Turret_Backup__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret_Backup__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret_Backup__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret_Backup__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret_Backup__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret_Backup__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret_Backup__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret_Backup__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret_Backup__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret_Backup__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret_Backup__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret_Backup__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret_Backup__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret_Backup__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret_Backup__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret_Backup__0__PC CYREG_PRT1_PC
#define Turret_Backup__0__PC2 CYREG_PRT1_PC2
#define Turret_Backup__0__PORT 1u
#define Turret_Backup__0__PS CYREG_PRT1_PS
#define Turret_Backup__0__SHIFT 4
#define Turret_Backup__DR CYREG_PRT1_DR
#define Turret_Backup__INTCFG CYREG_PRT1_INTCFG
#define Turret_Backup__INTSTAT CYREG_PRT1_INTSTAT
#define Turret_Backup__MASK 0x10u
#define Turret_Backup__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret_Backup__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret_Backup__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret_Backup__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret_Backup__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret_Backup__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret_Backup__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret_Backup__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret_Backup__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret_Backup__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret_Backup__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret_Backup__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret_Backup__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret_Backup__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret_Backup__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret_Backup__PC CYREG_PRT1_PC
#define Turret_Backup__PC2 CYREG_PRT1_PC2
#define Turret_Backup__PORT 1u
#define Turret_Backup__PS CYREG_PRT1_PS
#define Turret_Backup__SHIFT 4

/* Turret_MCU */
#define Turret_MCU__0__DM__MASK 0x38000u
#define Turret_MCU__0__DM__SHIFT 15
#define Turret_MCU__0__DR CYREG_PRT1_DR
#define Turret_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Turret_MCU__0__HSIOM_MASK 0x00F00000u
#define Turret_MCU__0__HSIOM_SHIFT 20u
#define Turret_MCU__0__INTCFG CYREG_PRT1_INTCFG
#define Turret_MCU__0__INTSTAT CYREG_PRT1_INTSTAT
#define Turret_MCU__0__MASK 0x20u
#define Turret_MCU__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret_MCU__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret_MCU__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret_MCU__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret_MCU__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret_MCU__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret_MCU__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret_MCU__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret_MCU__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret_MCU__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret_MCU__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret_MCU__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret_MCU__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret_MCU__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret_MCU__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret_MCU__0__PC CYREG_PRT1_PC
#define Turret_MCU__0__PC2 CYREG_PRT1_PC2
#define Turret_MCU__0__PORT 1u
#define Turret_MCU__0__PS CYREG_PRT1_PS
#define Turret_MCU__0__SHIFT 5
#define Turret_MCU__DR CYREG_PRT1_DR
#define Turret_MCU__INTCFG CYREG_PRT1_INTCFG
#define Turret_MCU__INTSTAT CYREG_PRT1_INTSTAT
#define Turret_MCU__MASK 0x20u
#define Turret_MCU__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Turret_MCU__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Turret_MCU__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Turret_MCU__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Turret_MCU__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Turret_MCU__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Turret_MCU__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Turret_MCU__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Turret_MCU__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Turret_MCU__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Turret_MCU__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Turret_MCU__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Turret_MCU__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Turret_MCU__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Turret_MCU__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Turret_MCU__PC CYREG_PRT1_PC
#define Turret_MCU__PC2 CYREG_PRT1_PC2
#define Turret_MCU__PORT 1u
#define Turret_MCU__PS CYREG_PRT1_PS
#define Turret_MCU__SHIFT 5

/* W_Flap */
#define W_Flap__0__DM__MASK 0x38000u
#define W_Flap__0__DM__SHIFT 15
#define W_Flap__0__DR CYREG_PRT2_DR
#define W_Flap__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define W_Flap__0__HSIOM_MASK 0x00F00000u
#define W_Flap__0__HSIOM_SHIFT 20u
#define W_Flap__0__INTCFG CYREG_PRT2_INTCFG
#define W_Flap__0__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap__0__MASK 0x20u
#define W_Flap__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define W_Flap__0__OUT_SEL_SHIFT 10u
#define W_Flap__0__OUT_SEL_VAL 3u
#define W_Flap__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap__0__PC CYREG_PRT2_PC
#define W_Flap__0__PC2 CYREG_PRT2_PC2
#define W_Flap__0__PORT 2u
#define W_Flap__0__PS CYREG_PRT2_PS
#define W_Flap__0__SHIFT 5
#define W_Flap__DR CYREG_PRT2_DR
#define W_Flap__INTCFG CYREG_PRT2_INTCFG
#define W_Flap__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap__MASK 0x20u
#define W_Flap__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap__PC CYREG_PRT2_PC
#define W_Flap__PC2 CYREG_PRT2_PC2
#define W_Flap__PORT 2u
#define W_Flap__PS CYREG_PRT2_PS
#define W_Flap__SHIFT 5

/* W_Flap_Backup */
#define W_Flap_Backup__0__DM__MASK 0x7000u
#define W_Flap_Backup__0__DM__SHIFT 12
#define W_Flap_Backup__0__DR CYREG_PRT2_DR
#define W_Flap_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define W_Flap_Backup__0__HSIOM_MASK 0x000F0000u
#define W_Flap_Backup__0__HSIOM_SHIFT 16u
#define W_Flap_Backup__0__INTCFG CYREG_PRT2_INTCFG
#define W_Flap_Backup__0__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap_Backup__0__MASK 0x10u
#define W_Flap_Backup__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap_Backup__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap_Backup__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap_Backup__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap_Backup__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap_Backup__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap_Backup__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap_Backup__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap_Backup__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap_Backup__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap_Backup__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap_Backup__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap_Backup__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap_Backup__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap_Backup__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap_Backup__0__PC CYREG_PRT2_PC
#define W_Flap_Backup__0__PC2 CYREG_PRT2_PC2
#define W_Flap_Backup__0__PORT 2u
#define W_Flap_Backup__0__PS CYREG_PRT2_PS
#define W_Flap_Backup__0__SHIFT 4
#define W_Flap_Backup__DR CYREG_PRT2_DR
#define W_Flap_Backup__INTCFG CYREG_PRT2_INTCFG
#define W_Flap_Backup__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap_Backup__MASK 0x10u
#define W_Flap_Backup__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap_Backup__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap_Backup__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap_Backup__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap_Backup__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap_Backup__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap_Backup__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap_Backup__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap_Backup__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap_Backup__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap_Backup__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap_Backup__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap_Backup__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap_Backup__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap_Backup__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap_Backup__PC CYREG_PRT2_PC
#define W_Flap_Backup__PC2 CYREG_PRT2_PC2
#define W_Flap_Backup__PORT 2u
#define W_Flap_Backup__PS CYREG_PRT2_PS
#define W_Flap_Backup__SHIFT 4

/* W_Flap_MCU */
#define W_Flap_MCU__0__DM__MASK 0xE00u
#define W_Flap_MCU__0__DM__SHIFT 9
#define W_Flap_MCU__0__DR CYREG_PRT2_DR
#define W_Flap_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define W_Flap_MCU__0__HSIOM_MASK 0x0000F000u
#define W_Flap_MCU__0__HSIOM_SHIFT 12u
#define W_Flap_MCU__0__INTCFG CYREG_PRT2_INTCFG
#define W_Flap_MCU__0__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap_MCU__0__MASK 0x08u
#define W_Flap_MCU__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap_MCU__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap_MCU__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap_MCU__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap_MCU__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap_MCU__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap_MCU__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap_MCU__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap_MCU__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap_MCU__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap_MCU__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap_MCU__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap_MCU__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap_MCU__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap_MCU__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap_MCU__0__PC CYREG_PRT2_PC
#define W_Flap_MCU__0__PC2 CYREG_PRT2_PC2
#define W_Flap_MCU__0__PORT 2u
#define W_Flap_MCU__0__PS CYREG_PRT2_PS
#define W_Flap_MCU__0__SHIFT 3
#define W_Flap_MCU__DR CYREG_PRT2_DR
#define W_Flap_MCU__INTCFG CYREG_PRT2_INTCFG
#define W_Flap_MCU__INTSTAT CYREG_PRT2_INTSTAT
#define W_Flap_MCU__MASK 0x08u
#define W_Flap_MCU__PA__CFG0 CYREG_UDB_PA2_CFG0
#define W_Flap_MCU__PA__CFG1 CYREG_UDB_PA2_CFG1
#define W_Flap_MCU__PA__CFG10 CYREG_UDB_PA2_CFG10
#define W_Flap_MCU__PA__CFG11 CYREG_UDB_PA2_CFG11
#define W_Flap_MCU__PA__CFG12 CYREG_UDB_PA2_CFG12
#define W_Flap_MCU__PA__CFG13 CYREG_UDB_PA2_CFG13
#define W_Flap_MCU__PA__CFG14 CYREG_UDB_PA2_CFG14
#define W_Flap_MCU__PA__CFG2 CYREG_UDB_PA2_CFG2
#define W_Flap_MCU__PA__CFG3 CYREG_UDB_PA2_CFG3
#define W_Flap_MCU__PA__CFG4 CYREG_UDB_PA2_CFG4
#define W_Flap_MCU__PA__CFG5 CYREG_UDB_PA2_CFG5
#define W_Flap_MCU__PA__CFG6 CYREG_UDB_PA2_CFG6
#define W_Flap_MCU__PA__CFG7 CYREG_UDB_PA2_CFG7
#define W_Flap_MCU__PA__CFG8 CYREG_UDB_PA2_CFG8
#define W_Flap_MCU__PA__CFG9 CYREG_UDB_PA2_CFG9
#define W_Flap_MCU__PC CYREG_PRT2_PC
#define W_Flap_MCU__PC2 CYREG_PRT2_PC2
#define W_Flap_MCU__PORT 2u
#define W_Flap_MCU__PS CYREG_PRT2_PS
#define W_Flap_MCU__SHIFT 3

/* CONTROL */
#define CONTROL__0__DM__MASK 0x07u
#define CONTROL__0__DM__SHIFT 0
#define CONTROL__0__DR CYREG_PRT2_DR
#define CONTROL__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define CONTROL__0__HSIOM_MASK 0x0000000Fu
#define CONTROL__0__HSIOM_SHIFT 0u
#define CONTROL__0__INTCFG CYREG_PRT2_INTCFG
#define CONTROL__0__INTSTAT CYREG_PRT2_INTSTAT
#define CONTROL__0__MASK 0x01u
#define CONTROL__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define CONTROL__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define CONTROL__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define CONTROL__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define CONTROL__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define CONTROL__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define CONTROL__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define CONTROL__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define CONTROL__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define CONTROL__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define CONTROL__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define CONTROL__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define CONTROL__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define CONTROL__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define CONTROL__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define CONTROL__0__PC CYREG_PRT2_PC
#define CONTROL__0__PC2 CYREG_PRT2_PC2
#define CONTROL__0__PORT 2u
#define CONTROL__0__PS CYREG_PRT2_PS
#define CONTROL__0__SHIFT 0
#define CONTROL__DR CYREG_PRT2_DR
#define CONTROL__INTCFG CYREG_PRT2_INTCFG
#define CONTROL__INTSTAT CYREG_PRT2_INTSTAT
#define CONTROL__MASK 0x01u
#define CONTROL__PA__CFG0 CYREG_UDB_PA2_CFG0
#define CONTROL__PA__CFG1 CYREG_UDB_PA2_CFG1
#define CONTROL__PA__CFG10 CYREG_UDB_PA2_CFG10
#define CONTROL__PA__CFG11 CYREG_UDB_PA2_CFG11
#define CONTROL__PA__CFG12 CYREG_UDB_PA2_CFG12
#define CONTROL__PA__CFG13 CYREG_UDB_PA2_CFG13
#define CONTROL__PA__CFG14 CYREG_UDB_PA2_CFG14
#define CONTROL__PA__CFG2 CYREG_UDB_PA2_CFG2
#define CONTROL__PA__CFG3 CYREG_UDB_PA2_CFG3
#define CONTROL__PA__CFG4 CYREG_UDB_PA2_CFG4
#define CONTROL__PA__CFG5 CYREG_UDB_PA2_CFG5
#define CONTROL__PA__CFG6 CYREG_UDB_PA2_CFG6
#define CONTROL__PA__CFG7 CYREG_UDB_PA2_CFG7
#define CONTROL__PA__CFG8 CYREG_UDB_PA2_CFG8
#define CONTROL__PA__CFG9 CYREG_UDB_PA2_CFG9
#define CONTROL__PC CYREG_PRT2_PC
#define CONTROL__PC2 CYREG_PRT2_PC2
#define CONTROL__PORT 2u
#define CONTROL__PS CYREG_PRT2_PS
#define CONTROL__SHIFT 0

/* Clock_1 */
#define Clock_1__DIVIDER_MASK 0x0000FFFFu
#define Clock_1__ENABLE CYREG_CLK_DIVIDER_C00
#define Clock_1__ENABLE_MASK 0x80000000u
#define Clock_1__MASK 0x80000000u
#define Clock_1__REGISTER CYREG_CLK_DIVIDER_C00

/* Clock_2 */
#define Clock_2__DIVIDER_MASK 0x0000FFFFu
#define Clock_2__ENABLE CYREG_CLK_DIVIDER_B00
#define Clock_2__ENABLE_MASK 0x80000000u
#define Clock_2__MASK 0x80000000u
#define Clock_2__REGISTER CYREG_CLK_DIVIDER_B00

/* Clock_4 */
#define Clock_4__DIVIDER_MASK 0x0000FFFFu
#define Clock_4__ENABLE CYREG_CLK_DIVIDER_A00
#define Clock_4__ENABLE_MASK 0x80000000u
#define Clock_4__MASK 0x80000000u
#define Clock_4__REGISTER CYREG_CLK_DIVIDER_A00

/* Shoulder */
#define Shoulder__0__DM__MASK 0x07u
#define Shoulder__0__DM__SHIFT 0
#define Shoulder__0__DR CYREG_PRT1_DR
#define Shoulder__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Shoulder__0__HSIOM_MASK 0x0000000Fu
#define Shoulder__0__HSIOM_SHIFT 0u
#define Shoulder__0__INTCFG CYREG_PRT1_INTCFG
#define Shoulder__0__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder__0__MASK 0x01u
#define Shoulder__0__OUT_SEL CYREG_UDB_PA1_CFG10
#define Shoulder__0__OUT_SEL_SHIFT 0u
#define Shoulder__0__OUT_SEL_VAL 0u
#define Shoulder__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder__0__PC CYREG_PRT1_PC
#define Shoulder__0__PC2 CYREG_PRT1_PC2
#define Shoulder__0__PORT 1u
#define Shoulder__0__PS CYREG_PRT1_PS
#define Shoulder__0__SHIFT 0
#define Shoulder__DR CYREG_PRT1_DR
#define Shoulder__INTCFG CYREG_PRT1_INTCFG
#define Shoulder__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder__MASK 0x01u
#define Shoulder__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder__PC CYREG_PRT1_PC
#define Shoulder__PC2 CYREG_PRT1_PC2
#define Shoulder__PORT 1u
#define Shoulder__PS CYREG_PRT1_PS
#define Shoulder__SHIFT 0

/* Shoulder_Backup */
#define Shoulder_Backup__0__DM__MASK 0x38u
#define Shoulder_Backup__0__DM__SHIFT 3
#define Shoulder_Backup__0__DR CYREG_PRT1_DR
#define Shoulder_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Shoulder_Backup__0__HSIOM_MASK 0x000000F0u
#define Shoulder_Backup__0__HSIOM_SHIFT 4u
#define Shoulder_Backup__0__INTCFG CYREG_PRT1_INTCFG
#define Shoulder_Backup__0__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder_Backup__0__MASK 0x02u
#define Shoulder_Backup__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder_Backup__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder_Backup__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder_Backup__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder_Backup__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder_Backup__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder_Backup__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder_Backup__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder_Backup__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder_Backup__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder_Backup__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder_Backup__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder_Backup__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder_Backup__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder_Backup__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder_Backup__0__PC CYREG_PRT1_PC
#define Shoulder_Backup__0__PC2 CYREG_PRT1_PC2
#define Shoulder_Backup__0__PORT 1u
#define Shoulder_Backup__0__PS CYREG_PRT1_PS
#define Shoulder_Backup__0__SHIFT 1
#define Shoulder_Backup__DR CYREG_PRT1_DR
#define Shoulder_Backup__INTCFG CYREG_PRT1_INTCFG
#define Shoulder_Backup__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder_Backup__MASK 0x02u
#define Shoulder_Backup__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder_Backup__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder_Backup__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder_Backup__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder_Backup__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder_Backup__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder_Backup__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder_Backup__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder_Backup__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder_Backup__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder_Backup__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder_Backup__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder_Backup__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder_Backup__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder_Backup__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder_Backup__PC CYREG_PRT1_PC
#define Shoulder_Backup__PC2 CYREG_PRT1_PC2
#define Shoulder_Backup__PORT 1u
#define Shoulder_Backup__PS CYREG_PRT1_PS
#define Shoulder_Backup__SHIFT 1

/* Shoulder_MCU */
#define Shoulder_MCU__0__DM__MASK 0x1C0u
#define Shoulder_MCU__0__DM__SHIFT 6
#define Shoulder_MCU__0__DR CYREG_PRT1_DR
#define Shoulder_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Shoulder_MCU__0__HSIOM_MASK 0x00000F00u
#define Shoulder_MCU__0__HSIOM_SHIFT 8u
#define Shoulder_MCU__0__INTCFG CYREG_PRT1_INTCFG
#define Shoulder_MCU__0__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder_MCU__0__MASK 0x04u
#define Shoulder_MCU__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder_MCU__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder_MCU__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder_MCU__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder_MCU__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder_MCU__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder_MCU__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder_MCU__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder_MCU__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder_MCU__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder_MCU__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder_MCU__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder_MCU__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder_MCU__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder_MCU__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder_MCU__0__PC CYREG_PRT1_PC
#define Shoulder_MCU__0__PC2 CYREG_PRT1_PC2
#define Shoulder_MCU__0__PORT 1u
#define Shoulder_MCU__0__PS CYREG_PRT1_PS
#define Shoulder_MCU__0__SHIFT 2
#define Shoulder_MCU__DR CYREG_PRT1_DR
#define Shoulder_MCU__INTCFG CYREG_PRT1_INTCFG
#define Shoulder_MCU__INTSTAT CYREG_PRT1_INTSTAT
#define Shoulder_MCU__MASK 0x04u
#define Shoulder_MCU__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Shoulder_MCU__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Shoulder_MCU__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Shoulder_MCU__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Shoulder_MCU__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Shoulder_MCU__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Shoulder_MCU__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Shoulder_MCU__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Shoulder_MCU__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Shoulder_MCU__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Shoulder_MCU__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Shoulder_MCU__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Shoulder_MCU__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Shoulder_MCU__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Shoulder_MCU__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Shoulder_MCU__PC CYREG_PRT1_PC
#define Shoulder_MCU__PC2 CYREG_PRT1_PC2
#define Shoulder_MCU__PORT 1u
#define Shoulder_MCU__PS CYREG_PRT1_PS
#define Shoulder_MCU__SHIFT 2

/* W_Rotate */
#define W_Rotate__0__DM__MASK 0x1C0u
#define W_Rotate__0__DM__SHIFT 6
#define W_Rotate__0__DR CYREG_PRT0_DR
#define W_Rotate__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define W_Rotate__0__HSIOM_MASK 0x00000F00u
#define W_Rotate__0__HSIOM_SHIFT 8u
#define W_Rotate__0__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate__0__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate__0__MASK 0x04u
#define W_Rotate__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define W_Rotate__0__OUT_SEL_SHIFT 4u
#define W_Rotate__0__OUT_SEL_VAL 2u
#define W_Rotate__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate__0__PC CYREG_PRT0_PC
#define W_Rotate__0__PC2 CYREG_PRT0_PC2
#define W_Rotate__0__PORT 0u
#define W_Rotate__0__PS CYREG_PRT0_PS
#define W_Rotate__0__SHIFT 2
#define W_Rotate__DR CYREG_PRT0_DR
#define W_Rotate__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate__MASK 0x04u
#define W_Rotate__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate__PC CYREG_PRT0_PC
#define W_Rotate__PC2 CYREG_PRT0_PC2
#define W_Rotate__PORT 0u
#define W_Rotate__PS CYREG_PRT0_PS
#define W_Rotate__SHIFT 2

/* W_Rotate_Backup */
#define W_Rotate_Backup__0__DM__MASK 0xE00u
#define W_Rotate_Backup__0__DM__SHIFT 9
#define W_Rotate_Backup__0__DR CYREG_PRT0_DR
#define W_Rotate_Backup__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define W_Rotate_Backup__0__HSIOM_MASK 0x0000F000u
#define W_Rotate_Backup__0__HSIOM_SHIFT 12u
#define W_Rotate_Backup__0__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate_Backup__0__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate_Backup__0__MASK 0x08u
#define W_Rotate_Backup__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate_Backup__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate_Backup__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate_Backup__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate_Backup__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate_Backup__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate_Backup__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate_Backup__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate_Backup__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate_Backup__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate_Backup__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate_Backup__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate_Backup__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate_Backup__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate_Backup__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate_Backup__0__PC CYREG_PRT0_PC
#define W_Rotate_Backup__0__PC2 CYREG_PRT0_PC2
#define W_Rotate_Backup__0__PORT 0u
#define W_Rotate_Backup__0__PS CYREG_PRT0_PS
#define W_Rotate_Backup__0__SHIFT 3
#define W_Rotate_Backup__DR CYREG_PRT0_DR
#define W_Rotate_Backup__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate_Backup__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate_Backup__MASK 0x08u
#define W_Rotate_Backup__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate_Backup__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate_Backup__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate_Backup__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate_Backup__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate_Backup__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate_Backup__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate_Backup__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate_Backup__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate_Backup__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate_Backup__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate_Backup__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate_Backup__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate_Backup__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate_Backup__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate_Backup__PC CYREG_PRT0_PC
#define W_Rotate_Backup__PC2 CYREG_PRT0_PC2
#define W_Rotate_Backup__PORT 0u
#define W_Rotate_Backup__PS CYREG_PRT0_PS
#define W_Rotate_Backup__SHIFT 3

/* W_Rotate_MCU */
#define W_Rotate_MCU__0__DM__MASK 0x7000u
#define W_Rotate_MCU__0__DM__SHIFT 12
#define W_Rotate_MCU__0__DR CYREG_PRT0_DR
#define W_Rotate_MCU__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define W_Rotate_MCU__0__HSIOM_MASK 0x000F0000u
#define W_Rotate_MCU__0__HSIOM_SHIFT 16u
#define W_Rotate_MCU__0__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate_MCU__0__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate_MCU__0__MASK 0x10u
#define W_Rotate_MCU__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate_MCU__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate_MCU__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate_MCU__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate_MCU__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate_MCU__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate_MCU__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate_MCU__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate_MCU__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate_MCU__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate_MCU__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate_MCU__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate_MCU__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate_MCU__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate_MCU__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate_MCU__0__PC CYREG_PRT0_PC
#define W_Rotate_MCU__0__PC2 CYREG_PRT0_PC2
#define W_Rotate_MCU__0__PORT 0u
#define W_Rotate_MCU__0__PS CYREG_PRT0_PS
#define W_Rotate_MCU__0__SHIFT 4
#define W_Rotate_MCU__DR CYREG_PRT0_DR
#define W_Rotate_MCU__INTCFG CYREG_PRT0_INTCFG
#define W_Rotate_MCU__INTSTAT CYREG_PRT0_INTSTAT
#define W_Rotate_MCU__MASK 0x10u
#define W_Rotate_MCU__PA__CFG0 CYREG_UDB_PA0_CFG0
#define W_Rotate_MCU__PA__CFG1 CYREG_UDB_PA0_CFG1
#define W_Rotate_MCU__PA__CFG10 CYREG_UDB_PA0_CFG10
#define W_Rotate_MCU__PA__CFG11 CYREG_UDB_PA0_CFG11
#define W_Rotate_MCU__PA__CFG12 CYREG_UDB_PA0_CFG12
#define W_Rotate_MCU__PA__CFG13 CYREG_UDB_PA0_CFG13
#define W_Rotate_MCU__PA__CFG14 CYREG_UDB_PA0_CFG14
#define W_Rotate_MCU__PA__CFG2 CYREG_UDB_PA0_CFG2
#define W_Rotate_MCU__PA__CFG3 CYREG_UDB_PA0_CFG3
#define W_Rotate_MCU__PA__CFG4 CYREG_UDB_PA0_CFG4
#define W_Rotate_MCU__PA__CFG5 CYREG_UDB_PA0_CFG5
#define W_Rotate_MCU__PA__CFG6 CYREG_UDB_PA0_CFG6
#define W_Rotate_MCU__PA__CFG7 CYREG_UDB_PA0_CFG7
#define W_Rotate_MCU__PA__CFG8 CYREG_UDB_PA0_CFG8
#define W_Rotate_MCU__PA__CFG9 CYREG_UDB_PA0_CFG9
#define W_Rotate_MCU__PC CYREG_PRT0_PC
#define W_Rotate_MCU__PC2 CYREG_PRT0_PC2
#define W_Rotate_MCU__PORT 0u
#define W_Rotate_MCU__PS CYREG_PRT0_PS
#define W_Rotate_MCU__SHIFT 4

/* Mux_timer_cy_m0s8_tcpwm_1 */
#define Mux_timer_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT1_CC
#define Mux_timer_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT1_CC_BUFF
#define Mux_timer_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT1_COUNTER
#define Mux_timer_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT1_CTRL
#define Mux_timer_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT1_INTR
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT1_INTR_MASK
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT1_INTR_MASKED
#define Mux_timer_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT1_INTR_SET
#define Mux_timer_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT1_PERIOD
#define Mux_timer_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT1_PERIOD_BUFF
#define Mux_timer_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT1_STATUS
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x02u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 1
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x200u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 9
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x2000000u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 25
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x20000u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 17
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x02u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 1
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x02u
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 1
#define Mux_timer_cy_m0s8_tcpwm_1__TCPWM_NUMBER 1u
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT1_TR_CTRL0
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT1_TR_CTRL1
#define Mux_timer_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT1_TR_CTRL2

/* Arm_select */
#define Arm_select__0__DM__MASK 0x38u
#define Arm_select__0__DM__SHIFT 3
#define Arm_select__0__DR CYREG_PRT0_DR
#define Arm_select__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Arm_select__0__HSIOM_MASK 0x000000F0u
#define Arm_select__0__HSIOM_SHIFT 4u
#define Arm_select__0__INTCFG CYREG_PRT0_INTCFG
#define Arm_select__0__INTSTAT CYREG_PRT0_INTSTAT
#define Arm_select__0__MASK 0x02u
#define Arm_select__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Arm_select__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Arm_select__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Arm_select__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Arm_select__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Arm_select__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Arm_select__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Arm_select__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Arm_select__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Arm_select__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Arm_select__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Arm_select__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Arm_select__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Arm_select__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Arm_select__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Arm_select__0__PC CYREG_PRT0_PC
#define Arm_select__0__PC2 CYREG_PRT0_PC2
#define Arm_select__0__PORT 0u
#define Arm_select__0__PS CYREG_PRT0_PS
#define Arm_select__0__SHIFT 1
#define Arm_select__DR CYREG_PRT0_DR
#define Arm_select__INTCFG CYREG_PRT0_INTCFG
#define Arm_select__INTSTAT CYREG_PRT0_INTSTAT
#define Arm_select__MASK 0x02u
#define Arm_select__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Arm_select__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Arm_select__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Arm_select__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Arm_select__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Arm_select__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Arm_select__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Arm_select__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Arm_select__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Arm_select__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Arm_select__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Arm_select__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Arm_select__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Arm_select__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Arm_select__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Arm_select__PC CYREG_PRT0_PC
#define Arm_select__PC2 CYREG_PRT0_PC2
#define Arm_select__PORT 0u
#define Arm_select__PS CYREG_PRT0_PS
#define Arm_select__SHIFT 1

/* Arm_select_in */
#define Arm_select_in__0__DM__MASK 0x38u
#define Arm_select_in__0__DM__SHIFT 3
#define Arm_select_in__0__DR CYREG_PRT2_DR
#define Arm_select_in__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Arm_select_in__0__HSIOM_MASK 0x000000F0u
#define Arm_select_in__0__HSIOM_SHIFT 4u
#define Arm_select_in__0__INTCFG CYREG_PRT2_INTCFG
#define Arm_select_in__0__INTSTAT CYREG_PRT2_INTSTAT
#define Arm_select_in__0__MASK 0x02u
#define Arm_select_in__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Arm_select_in__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Arm_select_in__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Arm_select_in__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Arm_select_in__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Arm_select_in__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Arm_select_in__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Arm_select_in__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Arm_select_in__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Arm_select_in__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Arm_select_in__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Arm_select_in__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Arm_select_in__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Arm_select_in__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Arm_select_in__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Arm_select_in__0__PC CYREG_PRT2_PC
#define Arm_select_in__0__PC2 CYREG_PRT2_PC2
#define Arm_select_in__0__PORT 2u
#define Arm_select_in__0__PS CYREG_PRT2_PS
#define Arm_select_in__0__SHIFT 1
#define Arm_select_in__DR CYREG_PRT2_DR
#define Arm_select_in__INTCFG CYREG_PRT2_INTCFG
#define Arm_select_in__INTSTAT CYREG_PRT2_INTSTAT
#define Arm_select_in__MASK 0x02u
#define Arm_select_in__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Arm_select_in__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Arm_select_in__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Arm_select_in__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Arm_select_in__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Arm_select_in__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Arm_select_in__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Arm_select_in__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Arm_select_in__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Arm_select_in__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Arm_select_in__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Arm_select_in__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Arm_select_in__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Arm_select_in__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Arm_select_in__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Arm_select_in__PC CYREG_PRT2_PC
#define Arm_select_in__PC2 CYREG_PRT2_PC2
#define Arm_select_in__PORT 2u
#define Arm_select_in__PS CYREG_PRT2_PS
#define Arm_select_in__SHIFT 1

/* Arm_select_timer_cy_m0s8_tcpwm_1 */
#define Arm_select_timer_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT2_CC
#define Arm_select_timer_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT2_CC_BUFF
#define Arm_select_timer_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT2_COUNTER
#define Arm_select_timer_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT2_CTRL
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT2_INTR
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT2_INTR_MASK
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT2_INTR_MASKED
#define Arm_select_timer_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT2_INTR_SET
#define Arm_select_timer_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT2_PERIOD
#define Arm_select_timer_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT2_PERIOD_BUFF
#define Arm_select_timer_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT2_STATUS
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x400u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 10
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x4000000u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 26
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x40000u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 18
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x04u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 2
#define Arm_select_timer_cy_m0s8_tcpwm_1__TCPWM_NUMBER 2u
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT2_TR_CTRL0
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT2_TR_CTRL1
#define Arm_select_timer_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT2_TR_CTRL2

/* Default_PWM_cy_m0s8_tcpwm_1 */
#define Default_PWM_cy_m0s8_tcpwm_1__CC CYREG_TCPWM_CNT0_CC
#define Default_PWM_cy_m0s8_tcpwm_1__CC_BUFF CYREG_TCPWM_CNT0_CC_BUFF
#define Default_PWM_cy_m0s8_tcpwm_1__COUNTER CYREG_TCPWM_CNT0_COUNTER
#define Default_PWM_cy_m0s8_tcpwm_1__CTRL CYREG_TCPWM_CNT0_CTRL
#define Default_PWM_cy_m0s8_tcpwm_1__INTR CYREG_TCPWM_CNT0_INTR
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_MASK CYREG_TCPWM_CNT0_INTR_MASK
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_MASKED CYREG_TCPWM_CNT0_INTR_MASKED
#define Default_PWM_cy_m0s8_tcpwm_1__INTR_SET CYREG_TCPWM_CNT0_INTR_SET
#define Default_PWM_cy_m0s8_tcpwm_1__PERIOD CYREG_TCPWM_CNT0_PERIOD
#define Default_PWM_cy_m0s8_tcpwm_1__PERIOD_BUFF CYREG_TCPWM_CNT0_PERIOD_BUFF
#define Default_PWM_cy_m0s8_tcpwm_1__STATUS CYREG_TCPWM_CNT0_STATUS
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMD CYREG_TCPWM_CMD
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_MASK 0x01u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDCAPTURE_SHIFT 0
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_MASK 0x100u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDRELOAD_SHIFT 8
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_MASK 0x1000000u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTART_SHIFT 24
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_MASK 0x10000u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CMDSTOP_SHIFT 16
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL CYREG_TCPWM_CTRL
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL_MASK 0x01u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_CTRL_SHIFT 0
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE CYREG_TCPWM_INTR_CAUSE
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_MASK 0x01u
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_INTR_CAUSE_SHIFT 0
#define Default_PWM_cy_m0s8_tcpwm_1__TCPWM_NUMBER 0u
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL0 CYREG_TCPWM_CNT0_TR_CTRL0
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL1 CYREG_TCPWM_CNT0_TR_CTRL1
#define Default_PWM_cy_m0s8_tcpwm_1__TR_CTRL2 CYREG_TCPWM_CNT0_TR_CTRL2

/* INPUT_SELECT */
#define INPUT_SELECT__0__DM__MASK 0x7000u
#define INPUT_SELECT__0__DM__SHIFT 12
#define INPUT_SELECT__0__DR CYREG_PRT3_DR
#define INPUT_SELECT__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define INPUT_SELECT__0__HSIOM_MASK 0x000F0000u
#define INPUT_SELECT__0__HSIOM_SHIFT 16u
#define INPUT_SELECT__0__INTCFG CYREG_PRT3_INTCFG
#define INPUT_SELECT__0__INTSTAT CYREG_PRT3_INTSTAT
#define INPUT_SELECT__0__MASK 0x10u
#define INPUT_SELECT__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define INPUT_SELECT__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define INPUT_SELECT__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define INPUT_SELECT__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define INPUT_SELECT__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define INPUT_SELECT__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define INPUT_SELECT__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define INPUT_SELECT__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define INPUT_SELECT__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define INPUT_SELECT__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define INPUT_SELECT__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define INPUT_SELECT__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define INPUT_SELECT__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define INPUT_SELECT__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define INPUT_SELECT__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define INPUT_SELECT__0__PC CYREG_PRT3_PC
#define INPUT_SELECT__0__PC2 CYREG_PRT3_PC2
#define INPUT_SELECT__0__PORT 3u
#define INPUT_SELECT__0__PS CYREG_PRT3_PS
#define INPUT_SELECT__0__SHIFT 4
#define INPUT_SELECT__1__DM__MASK 0x38000u
#define INPUT_SELECT__1__DM__SHIFT 15
#define INPUT_SELECT__1__DR CYREG_PRT3_DR
#define INPUT_SELECT__1__HSIOM CYREG_HSIOM_PORT_SEL3
#define INPUT_SELECT__1__HSIOM_MASK 0x00F00000u
#define INPUT_SELECT__1__HSIOM_SHIFT 20u
#define INPUT_SELECT__1__INTCFG CYREG_PRT3_INTCFG
#define INPUT_SELECT__1__INTSTAT CYREG_PRT3_INTSTAT
#define INPUT_SELECT__1__MASK 0x20u
#define INPUT_SELECT__1__PA__CFG0 CYREG_UDB_PA3_CFG0
#define INPUT_SELECT__1__PA__CFG1 CYREG_UDB_PA3_CFG1
#define INPUT_SELECT__1__PA__CFG10 CYREG_UDB_PA3_CFG10
#define INPUT_SELECT__1__PA__CFG11 CYREG_UDB_PA3_CFG11
#define INPUT_SELECT__1__PA__CFG12 CYREG_UDB_PA3_CFG12
#define INPUT_SELECT__1__PA__CFG13 CYREG_UDB_PA3_CFG13
#define INPUT_SELECT__1__PA__CFG14 CYREG_UDB_PA3_CFG14
#define INPUT_SELECT__1__PA__CFG2 CYREG_UDB_PA3_CFG2
#define INPUT_SELECT__1__PA__CFG3 CYREG_UDB_PA3_CFG3
#define INPUT_SELECT__1__PA__CFG4 CYREG_UDB_PA3_CFG4
#define INPUT_SELECT__1__PA__CFG5 CYREG_UDB_PA3_CFG5
#define INPUT_SELECT__1__PA__CFG6 CYREG_UDB_PA3_CFG6
#define INPUT_SELECT__1__PA__CFG7 CYREG_UDB_PA3_CFG7
#define INPUT_SELECT__1__PA__CFG8 CYREG_UDB_PA3_CFG8
#define INPUT_SELECT__1__PA__CFG9 CYREG_UDB_PA3_CFG9
#define INPUT_SELECT__1__PC CYREG_PRT3_PC
#define INPUT_SELECT__1__PC2 CYREG_PRT3_PC2
#define INPUT_SELECT__1__PORT 3u
#define INPUT_SELECT__1__PS CYREG_PRT3_PS
#define INPUT_SELECT__1__SHIFT 5
#define INPUT_SELECT__DR CYREG_PRT3_DR
#define INPUT_SELECT__INTCFG CYREG_PRT3_INTCFG
#define INPUT_SELECT__INTSTAT CYREG_PRT3_INTSTAT
#define INPUT_SELECT__MASK 0x30u
#define INPUT_SELECT__PA__CFG0 CYREG_UDB_PA3_CFG0
#define INPUT_SELECT__PA__CFG1 CYREG_UDB_PA3_CFG1
#define INPUT_SELECT__PA__CFG10 CYREG_UDB_PA3_CFG10
#define INPUT_SELECT__PA__CFG11 CYREG_UDB_PA3_CFG11
#define INPUT_SELECT__PA__CFG12 CYREG_UDB_PA3_CFG12
#define INPUT_SELECT__PA__CFG13 CYREG_UDB_PA3_CFG13
#define INPUT_SELECT__PA__CFG14 CYREG_UDB_PA3_CFG14
#define INPUT_SELECT__PA__CFG2 CYREG_UDB_PA3_CFG2
#define INPUT_SELECT__PA__CFG3 CYREG_UDB_PA3_CFG3
#define INPUT_SELECT__PA__CFG4 CYREG_UDB_PA3_CFG4
#define INPUT_SELECT__PA__CFG5 CYREG_UDB_PA3_CFG5
#define INPUT_SELECT__PA__CFG6 CYREG_UDB_PA3_CFG6
#define INPUT_SELECT__PA__CFG7 CYREG_UDB_PA3_CFG7
#define INPUT_SELECT__PA__CFG8 CYREG_UDB_PA3_CFG8
#define INPUT_SELECT__PA__CFG9 CYREG_UDB_PA3_CFG9
#define INPUT_SELECT__PC CYREG_PRT3_PC
#define INPUT_SELECT__PC2 CYREG_PRT3_PC2
#define INPUT_SELECT__PORT 3u
#define INPUT_SELECT__PS CYREG_PRT3_PS
#define INPUT_SELECT__SHIFT 4

/* Miscellaneous */
#define CY_VERSION "PSoC Creator  3.1 SP3"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 6u
#define CYDEV_CHIP_DIE_PSOC4A 3u
#define CYDEV_CHIP_DIE_PSOC5LP 5u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04C81193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 3u
#define CYDEV_CHIP_MEMBER_4D 2u
#define CYDEV_CHIP_MEMBER_4F 4u
#define CYDEV_CHIP_MEMBER_5A 6u
#define CYDEV_CHIP_MEMBER_5B 5u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0200
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
