/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Mux_timer.h>
#include <Clock_4.h>
#include <ISR.h>
#include <INPUT_SELECT.h>
#include <INPUT_SELECT_aliases.h>
#include <CONTROL.h>
#include <CONTROL_aliases.h>
#include <LED.h>
#include <LED_aliases.h>
#include <M_in_1.h>
#include <M_in_1_aliases.h>
#include <B_in_1.h>
#include <B_in_1_aliases.h>
#include <M_in_2.h>
#include <M_in_2_aliases.h>
#include <B_in_2.h>
#include <B_in_2_aliases.h>
#include <M_in_4.h>
#include <M_in_4_aliases.h>
#include <B_in_4.h>
#include <B_in_4_aliases.h>
#include <M_in_3.h>
#include <M_in_3_aliases.h>
#include <B_in_3.h>
#include <B_in_3_aliases.h>
#include <Out_1.h>
#include <Out_1_aliases.h>
#include <Out_2.h>
#include <Out_2_aliases.h>
#include <Out_4.h>
#include <Out_4_aliases.h>
#include <Out_3.h>
#include <Out_3_aliases.h>
#include <Default_PWM.h>
#include <Clock_1.h>
#include <ISR_1.h>
#include <M_in_5.h>
#include <M_in_5_aliases.h>
#include <B_in_5.h>
#include <B_in_5_aliases.h>
#include <Out_5.h>
#include <Out_5_aliases.h>
#include <Arm_select_timer.h>
#include <Clock_2.h>
#include <ISR_2.h>
#include <Arm_select.h>
#include <Arm_select_aliases.h>
#include <M_in_6.h>
#include <M_in_6_aliases.h>
#include <B_in_6.h>
#include <B_in_6_aliases.h>
#include <Out_6.h>
#include <Out_6_aliases.h>
#include <Arm_select_in.h>
#include <Arm_select_in_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

