/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Mux_timer.h>
#include <Clock_4.h>
#include <ISR.h>
#include <INPUT_SELECT.h>
#include <INPUT_SELECT_aliases.h>
#include <CONTROL.h>
#include <CONTROL_aliases.h>
#include <LED.h>
#include <LED_aliases.h>
#include <Turret_MCU.h>
#include <Turret_MCU_aliases.h>
#include <Turret_Backup.h>
#include <Turret_Backup_aliases.h>
#include <Shoulder_MCU.h>
#include <Shoulder_MCU_aliases.h>
#include <Shoulder_Backup.h>
#include <Shoulder_Backup_aliases.h>
#include <W_Rotate_MCU.h>
#include <W_Rotate_MCU_aliases.h>
#include <W_Rotate_Backup.h>
#include <W_Rotate_Backup_aliases.h>
#include <Elbow_MCU.h>
#include <Elbow_MCU_aliases.h>
#include <Elbow_Backup.h>
#include <Elbow_Backup_aliases.h>
#include <Turret.h>
#include <Turret_aliases.h>
#include <Shoulder.h>
#include <Shoulder_aliases.h>
#include <W_Rotate.h>
#include <W_Rotate_aliases.h>
#include <Elbow.h>
#include <Elbow_aliases.h>
#include <Default_PWM.h>
#include <Clock_1.h>
#include <ISR_1.h>
#include <W_Flap_MCU.h>
#include <W_Flap_MCU_aliases.h>
#include <W_Flap_Backup.h>
#include <W_Flap_Backup_aliases.h>
#include <W_Flap.h>
#include <W_Flap_aliases.h>
#include <Arm_select_timer.h>
#include <Clock_2.h>
#include <ISR_2.h>
#include <Arm_select.h>
#include <Arm_select_aliases.h>
#include <Hand_MCU.h>
#include <Hand_MCU_aliases.h>
#include <Hand_Backup.h>
#include <Hand_Backup_aliases.h>
#include <Hand.h>
#include <Hand_aliases.h>
#include <Arm_select_in.h>
#include <Arm_select_in_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

